export const ActivityKeyConstants = {
  STATUS_PROJECT: 2,
  VIEW: 'VIEW',
  VIEW_PLAN: 'VIEW_PLAN',
  ADD_PLAN: 'ADD_PLAN',
  EDIT_PLAN: 'EDIT_PLAN',
  DELETE_PLAN: 'DELETE_PLAN',
  EXPORT_RESOURCE_ALLOCATION: 'EXPORT_RESOURCE_ALLOCATION',
  EXPORT_PROJECT_ALLOCATION: 'EXPORT_PROJECT_ALLOCATION',
  EXPORT_RESOURCE_PROJECT: 'EXPORT_RESOURCE_PROJECT',
  EXPORT_PROJECT_BILLABLE: 'EXPORT_PROJECT_BILLABLE',
  EXPORT_BILLABLE_SUMMARY: 'EXPORT_BILLABLE_SUMMARY',
  EXPORT_LIST_PROJECT: 'EXPORT_LIST_PROJECT',
  EXPORT_LIST_PROJECT_DUL: 'EXPORT_LIST_PROJECT_DUL',
  EXPORT_ACTUAL_TIMESHEET_EFFORT: 'EXPORT_ACTUAL_TIMESHEET_EFFORT',
  EXPORT_RESOURCE_ALLOCATION_EFFORT: 'EXPORT_RESOURCE_ALLOCATION_EFFORT',
  EXPORT_ACTUAL_TIMESHEET_EFFORT_BY_ROLE:
    'EXPORT_ACTUAL_TIMESHEET_EFFORT_BY_ROLE',
  EXPORT_MVV_LIST: 'EXPORT_MVV_LIST_IN_PROJECT',
  EXPORT_PROJECT_ALLOCATION_REPORT: 'EXPORT_PROJECT_ALLOCATION_REPORT',
  EXPORT_PERFORMANCE_SCORE: 'EXPORT_PERFORMANCE_SCORE',
  VIEW_ALL_TIMESHEET: 'VIEW_ALL_TIMESHEET',
  VIEW_TIME_SHEET: 'VIEW_TIME_SHEET',
  RATE_PERFORMANCE: 'RATE_PERFORMANCE',
  RATE_ALL_PERFORMANCE: 'RATE_ALL_PERFORMANCE',
  ADMIN_APPROVE_TIMESHEET: 'ADMIN_APPROVE_TIMESHEET',
  ADMIN_EDIT_TIMESHEET: 'ADMIN_EDIT_TIMESHEET',
  PM_APPROVE_TIMESHEET: 'PM_APPROVE_TIMESHEET',
  PM_EDIT_TIMESHEET: 'PM_EDIT_TIMESHEET',
  SELECT_TOGGLE: 'SELECT_TOGGLE',
  ADD: 'ADD',
  EDIT: 'EDIT',
  DETAIL: 'DETAIL',
  DELETE: 'DELETE',
  VIEW_COMMENT: 'VIEW_COMMENT',
  ADD_COMMENT: 'ADD_COMMENT',
  EDIT_COMMENT: 'EDIT_COMMENT',
  VIEW_CSS: 'VIEW_CSS',
  CREATE_CSS: 'CREATE_CSS',
  EDIT_CSS: 'EDIT_CSS',
  VIEW_BILLABLE: 'VIEW_BILLABLE',
  ADD_BILLABLE: 'ADD_BILLABLE',
  EDIT_BILLABLE: 'EDIT_BILLABLE',
  DELETE_BILLABLE: 'DELETE_BILLABLE',
  VIEW_PCV_RATE: 'VIEW_PCV_RATE',
  ADD_PCV_RATE: 'ADD_PCV_RATE',
  EDIT_PCV_RATE: 'EDIT_PCV_RATE',
  DELETE_PCV_RATE: 'DELETE_PCV_RATE',
  VIEW_TIMELINE: 'VIEW_TIMELINE',
  ADD_TIMELINE: 'ADD_TIMELINE',
  EDIT_TIMELINE: 'EDIT_TIMELINE',
  DELETE_TIMELINE: 'DELETE_TIMELINE',
  DELETE_CSS_PROJECT: 'DELETE_CSS_PROJECT',
  SETTING_DU_EDIT: 'SETTING_DU_EDIT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  VIEW_PROJECT_INFORMATION: 'VIEW_PROJECT_INFORMATION',
  EDIT_PROJECT_INFORMATION: 'EDIT_PROJECT_INFORMATION',
  VIEW_PROJECT_ZONE: 'VIEW_PROJECT_ZONE',
  ADD_PROJECT_ZONE: 'ADD_PROJECT_ZONE',
  EDIT_PROJECT_ZONE: 'EDIT_PROJECT_ZONE',
  VIEW_PROJECT_MEMBER: 'VIEW_PROJECT_MEMBER',
  TEXT_BOX_PROJECT_MEMBER: 'TEXT_BOX_PROJECT_MEMBER',
  USER_DETAIL: 'USER_DETAIL',
  EDIT_USER: 'EDIT_USER',
  CHANGE_STATUS: 'CHANGE_STATUS',
  PROJECT_DETAIL: 'PROJECT_DETAIL',
  UPDATE_MANPOWER_DATA: 'UPDATE_MANPOWER_DATA',
  UPDATE_DU_STATISTIC: 'UPDATE_DU_STATISTIC',
  SYNC_BUSINESS_PLAN_SAP: 'SYNC_BUSINESS_PLAN_SAP',
  VIEW_PROJECT_NORM: 'VIEW_PROJECT_NORM',
  ADD_PROJECT_NORM: 'ADD_PROJECT_NORM',
  EDIT_PROJECT_NORM: 'EDIT_PROJECT_NORM',
  DELETE_PROJECT_NORM: 'DELETE_PROJECT_NORM',
  VIEW_DU_SETTING: 'VIEW_DU_SETTING',
  ADD_DU_SETTING: 'ADD_DU_SETTING',
  EDIT_DU_SETTING: 'EDIT_DU_SETTING',
  DELETE_DU_SETTING: 'DELETE_DU_SETTING',
  VIEW_COMPANY_DELIVERY: 'VIEW_COMPANY_DELIVERY',
  ADD_COMPANY_DELIVERY: 'ADD_COMPANY_DELIVERY',
  EDIT_COMPANY_DELIVERY: 'EDIT_COMPANY_DELIVERY',
  DELETE_COMPANY_DELIVERY: 'DELETE_COMPANY_DELIVERY',
  VIEW_SALE_SETTING: 'VIEW_SALE_SETTING',
  ADD_SALE_SETTING: 'ADD_SALE_SETTING',
  EDIT_SALE_SETTING: 'EDIT_SALE_SETTING',
  DELETE_SALE_SETTING: 'DELETE_SALE_SETTING',
  ADD_NOTE: 'ADD_NOTE',
  EDIT_NOTE: 'EDIT_NOTE',
  ADD_CSS_COMMENT: 'ADD_CSS_COMMENT',
  EDIT_CSS_COMMENT: 'EDIT_CSS_COMMENT',
  DELETE_CSS_COMMENT: 'DELETE_CSS_COMMENT',
  VIEW_CSS_COMMENT: 'VIEW_CSS_COMMENT',
  // Sale Pipeline key
  ADD_SALE_PIPELINE_NOTE: 'ADD_SALE_PIPELINE_NOTE',
  EDIT_SALE_PIPELINE_NOTE: 'EDIT_SALE_PIPELINE_NOTE',
  DELETE_SALE_PIPELINE_NOTE: 'DELETE_SALE_PIPELINE_NOTE',

  VIEW_SALE_OVERVIEW: 'VIEW_SALE_OVERVIEW',
  VIEW_SALE_PIPELINE: 'VIEW_SALE_PIPELINE',
  VIEW_SALE_LEAD: 'VIEW_SALE_LEAD',
  VIEW_SALE_ANALYTIC: 'VIEW_SALE_ANALYTIC',
  VIEW_SALE_CRM_PIPELINE: 'VIEW_SALE_CRM_PIPELINE',

  // Work Order

  ADD_WORK_ORDER: 'ADD_WORK_ORDER',
  UPDATE_WORK_ORDER: 'UPDATE_WORK_ORDER',
  VIEW_DETAIL_WORK_ORDER: 'VIEW_DETAIL_WORK_ORDER',
  VIEW_WORK_ORDER: 'VIEW_WORK_ORDER',
  CHANGE_STATUS_WORK_ORDER: 'CHANGE_STATUS_WORK_ORDER',
  DELETE_WORK_ORDER: 'DELETE_WORK_ORDER',

  //DELIVERY PLAN
  ADD_DELIVERY_PLAN: 'ADD_DELIVERY_PLAN',
  EDIT_DELIVERY_PLAN: 'EDIT_DELIVERY_PLAN',

  // SALE_PIPELINE_ADMIN: 'SALE_PIPELINE_ADMIN',
  // SALE_PIPELINE: 'SALE_PIPELINE',
  // SALE_PIPELINE_ADD: 'SALE_PIPELINE_ADD',
  // SALE_OVERVIEW_ADMIN: 'SALE_OVERVIEW_ADMIN',
  // SALES_LEAD_ADMIN: 'SALES_LEAD_ADMIN',
  // SALES_ANALYTIC_ADMIN: 'SALES_ANALYTIC_ADMIN'

  //holiday setting key
  VIEW_HOLIDAY_SETTING: 'VIEW_HOLIDAY_SETTING',
  ADD_HOLIDAY_SETTING: 'ADD_HOLIDAY_SETTING',
  EDIT_HOLIDAY_SETTING: 'EDIT_HOLIDAY_SETTING',
  DELETE_HOLIDAY_SETTING: 'DELETE_HOLIDAY_SETTING',

  // OPEN UPDATE CLOSE PROJECT NEW VERSION
  CREATE_CLOSE: 'CREATE_CLOSE',
  CREATE_UPDATE: 'CREATE_UPDATE',
  CREATE_OPEN_EXISTING: 'CREATE_OPEN_EXISTING',
  CREATE_OPEN_NEW: 'CREATE_OPEN_NEW',
  SEND_REQUEST: 'SEND_REQUEST',
  APPROVED_REJECT_PM: 'APPROVED_REJECT_PM',
  APPROVED_REJECT_SEPG: 'APPROVED_REJECT_SEPG',
  EDIT_STATUS_PENDING_SEPG: 'EDIT_STATUS_PENDING_SEPG',
  EDIT_STATUS_REJECT: 'EDIT_STATUS_REJECT',

  // ver 2
  VIEW_BY_PM: 'VIEW_BY_PM',
  VIEW_BY_DU: 'VIEW_BY_DU',
  VIEW_BY_G: 'VIEW_BY_G',
  VIEW_BY_CMC: 'VIEW_BY_CMC',
  APPROVE_OPEN_REQUEST: 'APPROVE_OPEN_REQUEST',
  REJECT_OPEN_REQUEST: 'REJECT_OPEN_REQUEST',
  EDIT_OPEN_REQUEST_BU: 'EDIT_OPEN_REQUEST_BU',
  EDIT_OPEN_REQUEST_G: 'EDIT_OPEN_REQUEST_G',
  EDIT_OPEN_REQUEST_ALL: 'EDIT_OPEN_REQUEST_ALL',
  EDIT_OPEN_REQUEST_PM: 'EDIT_OPEN_REQUEST_PM',
  APPROVE_REJECT_OPEN_REQUEST_PM: 'APPROVE_REJECT_OPEN_REQUEST_PM',
  APPROVE_UPDATE_REQUEST: 'APPROVE_UPDATE_REQUEST',
  REJECT_UPDATE_REQUEST: 'REJECT_UPDATE_REQUEST',
  EDIT_UPDATE_REQUEST: 'EDIT_UPDATE_REQUEST',
  CREATE_CLOSE_REQUEST: 'CREATE_CLOSE_REQUEST',
  SEND_CLOSE_REQUEST: 'SEND_CLOSE_REQUEST',
  APPROVE_CLOSE_REQUEST: 'APPROVE_CLOSE_REQUEST',
  REJECT_CLOSE_REQUEST: 'REJECT_CLOSE_REQUEST',
  EDIT_REQUEST_INFOR_CLOSE_REQUEST: 'EDIT_REQUEST_INFOR_CLOSE_REQUEST',
  EDIT_CHECKLIST_CLOSE_REQUEST: 'EDIT_CHECKLIST_CLOSE_REQUEST',
  VIEW_PROJECT_REQUEST_LIST_PM: 'VIEW_PROJECT_REQUEST_LIST_PM',
  VIEW_PROJECT_REQUEST_LIST_DUL: 'VIEW_PROJECT_REQUEST_LIST_DUL',
  VIEW_PROJECT_REQUEST_LIST_SALE: 'VIEW_PROJECT_REQUEST_LIST_SALE',
  VIEW_PROJECT_REQUEST_LIST_ASSIGNEE: 'VIEW_PROJECT_REQUEST_LIST_ASSIGNEE',
  VIEW_PROJECT_REQUEST_LIST: 'VIEW_PROJECT_REQUEST_LIST',
  SUBMIT_OPEN_REQUEST: 'SUBMIT_OPEN_REQUEST',
  SUBMIT_UPDATE_REQUEST: 'SUBMIT_UPDATE_REQUEST',
  EDIT_UPDATE_REQUEST_BU: 'EDIT_UPDATE_REQUEST_BU',
  EDIT_UPDATE_REQUEST_G: 'EDIT_UPDATE_REQUEST_G',
  EDIT_UPDATE_REQUEST_ALL: 'EDIT_UPDATE_REQUEST_ALL',
  EDIT_UPDATE_REQUEST_PM: 'EDIT_UPDATE_REQUEST_PM',
  APPROVE_REJECT_UPDATE_REQUEST_PM: 'APPROVE_REJECT_UPDATE_REQUEST_PM',

  EDIT_CLOSE_REQUEST_PM: 'EDIT_CLOSE_REQUEST_PM',
  EDIT_CLOSE_REQUEST_ALL: 'EDIT_CLOSE_REQUEST_ALL',
  EDIT_CLOSE_REQUEST_QA: 'EDIT_CLOSE_REQUEST_QA',
  SUBMIT_CLOSE_REQUEST: 'SUBMIT_CLOSE_REQUEST',
  APPROVE_REJECT_CLOSE_REQUEST_QA: 'APPROVE_REJECT_CLOSE_REQUEST_QA',
  APPROVE_REJECT_CLOSE_REQUEST_ALL: 'APPROVE_REJECT_CLOSE_REQUEST_ALL',
  EDIT_PERMISSION_STATUS_SEPG: 'EDIT_PERMISSION_STATUS_SEPG',

  //PROJETC INFORMATION
  QA_EDIT_PROJECT_INFO: 'QA_EDIT_PROJECT_INFO',
  PM_EDIT_PROJECT_INFO: 'PM_EDIT_PROJECT_INFO',
  SEPG_EDIT_PROJECT_INFO: 'SEPG_EDIT_PROJECT_INFO',
  ADMIN_EDIT_PROJECT_INFO: 'ADMIN_EDIT_PROJECT_INFO',
  QAL_EDIT_PROJECT_INFO: 'QAL_EDIT_PROJECT_INFO',
  //PROJECT LIST
  EXPORT_PROJECT_LIST: 'EXPORT_PROJECT_LIST',

  // WO LIST
  VIEW_ALL_WORK_ORDER: 'VIEW_ALL_WORK_ORDER',
  VIEW_WORK_ORDER_DU: 'VIEW_WORK_ORDER_DU',
  VIEW_WORK_ORDER_G: 'VIEW_WORK_ORDER_G',
  SALE_VIEW_WORK_ORDER: 'SALE_VIEW_WORK_ORDER',
  VIEW_WO_DETAIL: 'VIEW_WO_DETAIL',
  DU_VIEW_ALL_WORK_ORDER: 'DU_VIEW_ALL_WORK_ORDER',

  // KPI TAILORING
  VIEW_KPI_TAILORING: 'VIEW_KPI_TAILORING',
  QA_EDIT_KPI_TAILORING: 'QA_EDIT_KPI_TAILORING',
  ADMIN_EDIT_KPI_TAILORING: 'ADMIN_EDIT_KPI_TAILORING',

  // New PCV
  QA_ADD_PCV_RATE: 'QA_ADD_PCV_RATE',
  ADMIN_ADD_PCV_RATE: 'ADMIN_ADD_PCV_RATE',
  QA_EDIT_PCV_RATE: 'QA_EDIT_PCV_RATE',
  ADMIN_EDIT_PCV_RATE: 'ADMIN_EDIT_PCV_RATE',
  VIEW_ALL_PCV_RATE: 'VIEW_ALL_PCV_RATE',
  ADMIN_DELETE_PCV_RATE: 'ADMIN_DELETE_PCV_RATE',
  QA_DELETE_PCV_RATE: 'QA_DELETE_PCV_RATE',

  QA_CREATE_CSS: 'QA_CREATE_CSS',
  ADMIN_CREATE_CSS: 'ADMIN_CREATE_CSS',
  QA_EDIT_CSS: 'QA_EDIT_CSS',
  ADMIN_EDIT_CSS: 'ADMIN_EDIT_CSS',
  VIEW_ALL_CSS: 'VIEW_ALL_CSS',
  ADMIN_DELETE_CSS: 'ADMIN_DELETE_CSS',
  QA_DELETE_CSS: 'QA_DELETE_CSS',

  VIEW_ALL_TIMELINE: 'VIEW_ALL_TIMELINE',
  VIEW_ALL_LEAKAGE_RATE: 'VIEW_ALL_LEAKAGE_RATE',
  VIEW_ALL_BUG_RATE: 'VIEW_ALL_BUG_RATE',

  VIEW_PCV_TEMPLATE: 'VIEW_PCV_TEMPLATE',
  QA_EDIT_PCV_TEMPLATE: 'QA_EDIT_PCV_TEMPLATE',
  ADMIN_EDIT_PCV_TEMPLATE: 'ADMIN_EDIT_PCV_TEMPLATE',

  // WORKFLOW
  VIEW_WORKFLOW_LIST_SETTING: 'VIEW_WORKFLOW_LIST_SETTING',
  VIEW_GROUPS_WORKFLOW_SETTING: 'VIEW_GROUPS_WORKFLOW_SETTING',
  CREATE_GROUPS_WORKFLOW_SETTING: 'CREATE_GROUPS_WORKFLOW_SETTING',
  EDIT_GROUPS_WORKFLOW_SETTING: 'EDIT_GROUPS_WORKFLOW_SETTING',
  VIEW_PERMISSION_WORKFLOW_SETTING: 'VIEW_PERMISSION_WORKFLOW_SETTING',
  MANAGE_EMAIL_SETTING: 'MANAGE_EMAIL_SETTING',

  // BUSINESS PLAN
  VIEW_BUSINESS_PLAN_LIST: 'VIEW_BUSINESS_PLAN_LIST',
  VIEW_BUSINESS_PLAN_REQUEST_ALL: 'VIEW_BUSINESS_PLAN_REQUEST_ALL',
  VIEW_BUSINESS_PLAN_REQUEST_ASSIGNEE: 'VIEW_BUSINESS_PLAN_REQUEST_ASSIGNEE',
  EDIT_BUSINESS_PLAN: 'EDIT_BUSINESS_PLAN',
  EDIT_BUSINESS_PLAN_ALL: 'EDIT_BUSINESS_PLAN_ALL',
  EDIT_DOCUMENT_ALL: 'EDIT_DOCUMENT_ALL',
  EDIT_DOCUMENT_DU: 'EDIT_DOCUMENT_DU',
  CREATE_NEW_VERSION: 'CREATE_NEW_VERSION',
  VIEW_BUSINESS_PLAN_LIST_WORKFLOW: 'VIEW_BUSINESS_PLAN_LIST_WORKFLOW',
  VIEW_BUSINESS_PLAN_LIST_SALE: 'VIEW_BUSINESS_PLAN_LIST_SALE',
  VIEW_BUSINESS_PLAN_LIST_DUL: 'VIEW_BUSINESS_PLAN_LIST_DUL',
  VIEW_BUSINESS_PLAN_LIST_PRESALE: 'VIEW_BUSINESS_PLAN_LIST_PRESALE',
  VIEW_BUSINESS_PLAN_LIST_ADVISER: 'VIEW_BUSINESS_PLAN_LIST_ADVISER',
  VIEW_BUSINESS_PLAN_LIST_PREPARATOR: 'VIEW_BUSINESS_PLAN_LIST_PREPARATOR',
  VIEW_BUSINESS_PLAN_LIST_PM: 'VIEW_BUSINESS_PLAN_LIST_PM',
  VIEW_BUSINESS_PLAN_LIST_BUL: 'VIEW_BUSINESS_PLAN_LIST_BUL',
  EXPORT_BUSINESS_PLAN: 'EXPORT_BUSINESS_PLAN',
  SUBMIT_BUSINESS_PLAN: 'SUBMIT_BUSINESS_PLAN',

  // BUSINESS PLAN - REVENUE
  EDIT_REVENUE_PLAN_ALL_STATUS: 'EDIT_REVENUE_PLAN_ALL_STATUS',
  // BUSINESS PLAN - DELIVERY
  EDIT_DELIVERY_PLAN_ALL_STATUS: 'EDIT_DELIVERY_PLAN_ALL_STATUS',

  // OPEN_UPDATE_REQUEST_NEW
  CREATE_REQUEST: 'CREATE_REQUEST',
  CREATE_OPEN_REQUEST_BU: 'CREATE_OPEN_REQUEST_BU',
  CREATE_OPEN_REQUEST_ALL: 'CREATE_OPEN_REQUEST_ALL',
  CREATE_OPEN_REQUEST_G: 'CREATE_OPEN_REQUEST_G',
  CREATE_UPDATE_REQUEST_BU: 'CREATE_UPDATE_REQUEST_BU',
  CREATE_UPDATE_REQUEST_ALL: 'CREATE_UPDATE_REQUEST_ALL',
  CREATE_UPDATE_REQUEST_G: 'CREATE_UPDATE_REQUEST_G',

  // PERFORMANCE SCORE SETTING
  EDIT_UPDATE_SETTING: 'EDIT_UPDATE_SETTING',
  VIEW_SETTING: 'VIEW_SETTING',

  // RATECARD SETTING
  VIEW_RATECARD_SETTING: 'VIEW_RATECARD_SETTING',
  ADD_RATECARD_SETTING: 'ADD_RATECARD_SETTING',
  EDIT_RATECARD_SETTING: 'EDIT_RATECARD_SETTING',

  // LABOR RATE SETTING
  VIEW_LABOR_RATE_SETTING: 'VIEW_LABOR_RATE_SETTING',
  EDIT_LABOR_RATE_SETTING: 'EDIT_LABOR_RATE_SETTING',

  // WARNING_NORMS_SETTING
  VIEW_WARNING_NORMS_SETTING: 'VIEW_WARNING_NORMS_SETTING',

  VIEW_ALLOCATION_VALIDATION_SETTING: 'VIEW_ALLOCATION_VALIDATION_SETTING',
  EDIT_ALLOCATION_VALIDATION_SETTING: 'EDIT_ALLOCATION_VALIDATION_SETTING',

  // DPM
  DPM_SEND_PLANNING_TO_SAP: 'DPM_SEND_PLANNING_TO_SAP',
  DPM_HISTORY_SEND_PLANNING_TO_SAP: 'DPM_HISTORY_SEND_PLANNING_TO_SAP',
  DPM_VIEW_ALL: 'DPM_VIEW_ALL',
  DPM_MANAGER_VIEW_BY_G: 'DPM_MANAGER_VIEW_BY_G',
  DPM_VIEW_BY_G: 'DPM_VIEW_BY_G',
  DPM_MANAGER_VIEW_BY_BU: 'DPM_MANAGER_VIEW_BY_BU',
  DPM_MANAGER_VIEW_BY_DU: 'DPM_MANAGER_VIEW_BY_DU',
  DPM_VIEW_BY_DU: 'DPM_VIEW_BY_DU',
  DPM_SALE_VIEW_BY_G: 'DPM_SALE_VIEW_BY_G',
  DPM_SALE_VIEW_BY_BU: 'DPM_SALE_VIEW_BY_BU',
  DPM_EDIT: 'DPM_EDIT',
  ADMIN_EDIT_DPM: 'ADMIN_EDIT_DPM',
  DPM_Export: 'DPM_Export',
  VIEW_DPM_HISTORY: 'VIEW_DPM_HISTORY',

  // SAP
  VIEW_SAP_BUSINESS_PLAN_REPORT_ALL: 'VIEW_SAP_BUSINESS_PLAN_REPORT_ALL',
  EXPORT_SAP_BUSINESS_PLAN_REPORT: 'EXPORT_SAP_BUSINESS_PLAN_REPORT',
  VIEW_DETAIL_SAP_BUSINESS_PLAN_REPORT: 'VIEW_DETAIL_SAP_BUSINESS_PLAN_REPORT',
  VIEW_SAP_BUSINESS_PLAN_REPORT_BUL: 'VIEW_SAP_BUSINESS_PLAN_REPORT_BUL',
  VIEW_SAP_BUSINESS_PLAN_REPORT_DUL: 'VIEW_SAP_BUSINESS_PLAN_REPORT_DUL',

  // PROJECT_MEMBER_STATUS REPORT
  VIEW_PROJECT_MEMBER_STATUS_REPORT: 'VIEW_PROJECT_MEMBER_STATUS_REPORT',
  EXPORT_PROJECT_MEMBER_STATUS_REPORT: 'EXPORT_PROJECT_MEMBER_STATUS_REPORT',

  // BUSINESS PLAN SETTING
  CONFIG_NORM_SETTING_ALL: 'CONFIG_NORM_SETTING_ALL',

  // Global Overview
  GLOBAL_OVERVIEW_DU_MANAGER: 'GLOBAL_OVERVIEW_DU_MANAGER',
  GLOBAL_OVERVIEW_DU_MEMBER: 'GLOBAL_OVERVIEW_DU_MEMBER',
  GLOBAL_OVERVIEW_G_MANAGER: 'GLOBAL_OVERVIEW_G_MANAGER',
  GLOBAL_OVERVIEW_G_MEMBER: 'GLOBAL_OVERVIEW_G_MEMBER',
  GLOBAL_OVERVIEW_ALL: 'GLOBAL_OVERVIEW_ALL',

  // Close Request
  CREATE_CLOSE_REQUEST_PM: 'CREATE_CLOSE_REQUEST_PM',
  CREATE_CLOSE_REQUEST_ALL: 'CREATE_CLOSE_REQUEST_ALL',

  // MVV Project Bonus
  VIEW_MVV_PROJECT_BONUS_CONFIG: 'VIEW_MVV_PROJECT_BONUS_CONFIG',
  EDIT_MVV_PROJECT_BONUS_CONFIG: 'EDIT_MVV_PROJECT_BONUS_CONFIG',
  EXPORT_MVV_PROJECT_BONUS_CONFIG: 'EXPORT_MVV_PROJECT_BONUS_CONFIG',
  VIEW_PERFORMANCE_BONUS_CONFIG: 'VIEW_PERFORMANCE_BONUS_CONFIG',
  EDIT_PERFORMANCE_BONUS_CONFIG: 'EDIT_PERFORMANCE_BONUS_CONFIG',
  VIEW_PERFORMANCE_RATE_CONFIG: 'VIEW_PERFORMANCE_RATE_CONFIG',

  // Performance & Bonus
  VIEW_PERFORMANCE_BY_MEMBER: 'VIEW_PERFORMANCE_BY_MEMBER',
  VIEW_PERFORMANCE_BY_PM: 'VIEW_PERFORMANCE_BY_PM',
  VIEW_PERFORMANCE_BY_DU_MEMBER: 'VIEW_PERFORMANCE_BY_DU_MEMBER',
  VIEW_PERFORMANCE_BY_DU_MANAGER: 'VIEW_PERFORMANCE_BY_DU_MANAGER',
  VIEW_PERFORMANCE_BY_DUL_MANAGER: 'VIEW_PERFORMANCE_BY_DUL_MANAGER',
  VIEW_PERFORMANCE_BY_G_MEMBER: 'VIEW_PERFORMANCE_BY_G_MEMBER',
  VIEW_PERFORMANCE_BY_G_MANAGER: 'VIEW_PERFORMANCE_BY_G_MANAGER',
  VIEW_PERFORMANCE_ALL: 'VIEW_PERFORMANCE_ALL',
  EXPORT_PERFORMANCE: 'EXPORT_PERFORMANCE',
  EXPORT_PERFORMANCE_BY_PM: 'EXPORT_PERFORMANCE_BY_PM',
  EXPORT_PERFORMANCE_BY_DU_MANAGER: 'EXPORT_PERFORMANCE_BY_DU_MANAGER',
  VIEW_HISTORY_PERFORMANCE: 'VIEW_HISTORY_PERFORMANCE',
  EDIT_PERFORMANCE: 'EDIT_PERFORMANCE',
  VIEW_HISTORY_PERFORMANCE_BY_MEMBER: 'VIEW_HISTORY_PERFORMANCE_BY_MEMBER',
  VIEW_HISTORY_PERFORMANCE_ALL: 'VIEW_HISTORY_PERFORMANCE_ALL',
  EDIT_RANK_PERFORMANCE: 'EDIT_RANK_PERFORMANCE',
  // Sync POA User
  SYNC_POA_USER_DATA: 'SYNC_POA_USER_DATA',
  //Project Member
  UPDATE_CURRENT_PM: 'UPDATE_CURRENT_PM',
  VIEW_LOG_MEMBER_HISTORY: 'VIEW_LOG_MEMBER_HISTORY',

  // Activate Backdate Allocation
  ACTIVATE_BACKDATE_ALLOCATION: 'ACTIVATE_BACKDATE_ALLOCATION',
  ADD_EDIT_PLAN_BACKDATE: 'ADD_EDIT_PLAN_BACKDATE',
  ADD_EDIT_PLAN_BACKDATE_PROJECT_RESOURCE:
    'ADD_EDIT_PLAN_BACKDATE_PROJECT_RESOURCE',

  // Performance Rank Setting
  VIEW_RANKING_SETTING: 'VIEW_RANKING_SETTING',
  EDIT_RANKING_SETTING: 'EDIT_RANKING_SETTING',
}
export const SourceConstants = {
  GLOBAL_OVERVIEW: '/dashboard/global/overview',
  GLOBAL_SALES: '/dashboard/global/sales',
  GLOBAL_DELIVERY: '/dashboard/global/delivery',
  GLOBAL_HR: '/dashboard/global/hr',
  DELIVERY_OVERVIEW: '/dashboard/delivery/overview',
  DELIVERY_RESOURCES: '/delivery/delivery-resources',
  DELIVERY_MONITORING: '/dashboard/delivery/monitoring',
  DELIVERY_ISSUE: '/dashboard/delivery/issue',
  DELIVERY_RISK: '/dashboard/delivery/risk',
  DELIVERY_REPORTS: '/dashboard/delivery/reports',
  DELIVERY_AVAILABLE_RESOURCE: '/dashboard/delivery/available-resource',
  REPORTS_RESOURCE_ALLOCATION:
    '/dashboard/delivery/reports/resource-allocation',
  REPORTS_PROJECT_ALLOCATION: '/dashboard/delivery/reports/project-allocation',
  REPORTS_RESOURCE_IN_PROJECT:
    '/dashboard/delivery/reports/resource-in-project',
  REPORTS_PROJECT_BILLABLE: '/dashboard/delivery/reports/project-billable',
  REPORTS_BILLABLE_SUMMARY: '/dashboard/delivery/reports/billable-summary',
  REPORTS_ACTUAL_TIMESHEET_EFFORT:
    '/dashboard/delivery/reports/actual-timesheet-effort',
  REPORTS_PROJECT_LIST: '/dashboard/delivery/reports/project-list',
  REPORTS_RESOURCE_ALLOCATION_NEW:
    '/dashboard/delivery/reports/resource-allocation-new',
  REPORTS_ACTUAL_TIMESHEET_EFFORT_BY_ROLE:
    '/dashboard/delivery/reports/actual-timesheet-effort-by-role',
  REPORTS_MVV_LIST_IN_PROJECT:
    '/dashboard/delivery/reports/mvv-list-in-project',
  REPORTS_PERFORMANCE_SCORE:
    '/dashboard/delivery/reports/performance-score-reports',
  REPORTS_PERFORMANCE_SCORE_BY_DAY:
    '/dashboard/delivery/reports/performance-score-reports-by-day',
  REPORTS_SAP: '/dashboard/delivery/reports/sap-report',
  REPORTS_SAP_DETAIL:
    '/dashboard/delivery/reports/sap-report/{duName}/{projectCode}',
  REPORTS_PROJECT_MEMBER_STATUS:
    '/dashboard/delivery/reports/project-member-status',

  PROJECTS_LIST: '/delivery/project-list',
  PROJECT_MEMBER: '/delivery/project-list/{projectId}/project-member',
  PROJECT_RESOURCE_ALLOCATE:
    '/delivery/project-list/{projectId}/project-resources',
  PROJECT_ISSUE: '/delivery/project-list/{projectId}/project-issues',
  PROJECT_RISK: '/delivery/project-list/{projectId}/project-risks',
  PROJECT_RISK_DETAIL:
    '/delivery/project-list/{projectId}/project-risks/{riskId}',
  PROJECT_MONITOR_REPORT:
    '/delivery/project-list/{projectId}/project-monitoring',
  PROJECT_INPUTS: '/delivery/project-list/{projectId}/project-inputs',
  PROJECT_WO_LIST: '/delivery/wo-list',
  PROJECT_WO_OVERVIEW: '/delivery/wo-list/{woId}/wo-overview',
  PROJECT_SETTING: '/delivery/project-list/{projectId}/project-setting',
  PROJECT_STATISTIC: '/dashboard/delivery/project-statistics',
  TASKS_PROJECT_REQUEST_LIST: '/tasks/project-request-list',
  SETTING_USERS: '/setting/general-setting/users',
  SETTING_GROUPS: '/setting/general-setting/groups',
  SETTING_PROJECT_TYPE: '/setting/delivery-setting/project-types',
  SETTING_PROJECTS: '/setting/delivery-setting/setting-projects',
  SETTING_PROJECT_NORMS: '/setting/delivery-setting/project-norms',
  SETTING_SYSTEM_UPDATE_MANPOWER:
    '/setting/system-support/update-manpower-data',
  SETTING_SKILL: '/setting/delivery-setting/skill-setting',
  SETTING_LOGS: '/setting/system-support/logs',
  SETTING_TIMESHEET: '/setting/delivery-setting/timesheet-settings',
  SETTING_HOLIDAY: '/setting/delivery-setting/holiday-setting',
  SETTING_PERFORMANCE_SCORE:
    '/setting/delivery-setting/performance-score-setting',
  SETTING_UPDATE_DU_STATISTIC: '/setting/system-support/update-du-statistic',
  SETTING_UPDATE_SAP_DATA: '/setting/system-support/update-sap-data',
  PROJECT_OVERVIEW: '/delivery/project-list/{projectId}/project-overview',
  PERFORMANCE_AND_BONUS: '/delivery/performance-and-bonus',
  // Old Page
  ADMIN_ROLE: '/admin/role',
  ADMIN_PERMISSION: '/admin/permission',
  ADMIN_USER_ROLE: '/admin/user-role',
  ADMIN_ROLE_PERMISSION: '/admin/role-permission',
  ADMIN_PERMISSION_DETAIL: '/admin/permission/permission-detail',
  ADMIN_ADD_PERMISSION: '/admin/permission/add-permission',
  //
  // Old Settings (Another Setting)
  ADMIN_SETTING: '/admin/setting',
  //
  ADMIN_COMPANY_SETTING: '/dashboard/dashboard-setting',
  SALES_OVERVIEW: '/dashboard/sales/overview',
  SALES_PIPELINE: '/dashboard/sales/progress',
  SALES_LEAD: '/dashboard/sale/lead',
  SALE_ANALYTIC: '/dashboard/sales/productivity',
  SALE_CRM_PIPELINE: '/dashboard/sales/dpm',
  MY_TIMESHEET: '/delivery/actual-timesheets',
  ACTUAL_BILLABLE: '/delivery/actual-billable',
  SALES_PRODUCTIVITY: '/dashboard/sale/productivity',
  SALES_KPI: '/dashboard/sales/kpi',
  DELIVERY_PLAN: '/delivery/delivery-plan',
  DELIVERY_PLAN_ADD: '/delivery/delivery-plan/add',
  DELIVERY_PLAN_EDIT: '/delivery/delivery-plan/edit',
  DELIVERY_WORK_ORDER: '/delivery/workorder',
  DELIVERY_WORK_ORDER_ADD: '/delivery/workorder/add',
  PROJECT_OPEN_NEW_WITH_ID: '/tasks/project-open-new/{requestId}',
  PROJECT_OPEN_NEW_WITHOUT_ID: '/tasks/project-open-new',
  PROJECT_UPDATE_DETAIL_WITH_ID: '/tasks/project-update-detail/{requestId}',
  PROJECT_UPDATE_DETAIL_WITHOUT_ID: '/tasks/project-update-detail',
  PROJECT_CLOSE_DETAIL: '/tasks/project-close-detail',
  PROJECT_CLOSE_DETAIL_WITH_ID: '/tasks/project-close-detail/{requestId}',
  DELIVERY_PROJECT_ISSUE_UPDATE:
    '/delivery/project-list/{projectId}/project-issues/{issueId}/update',
  PROJECT_KPI: '/delivery/project-list/{projectId}/project-kpi',

  // Business Plan
  BUSINESS_PLAN_LIST: '/delivery/business-plan-list',
  BUSINESS_PLAN_DETAIL:
    '/delivery/business-plan-list/{buId}/business-plan-detail',
  BUSINESS_PLAN_REQUEST: '/tasks/business-plan-request',

  // Workflow
  WORKFLOW_GROUPS: '/setting/workflow-setting/groups',
  WORKFLOW_WORKFLOWS: '/setting/workflow-setting/workflows',
  WORKFLOW_WORKFLOWS_DETAIL: '/setting/workflow-setting/workflows/{id}',
  WORKFLOW_PERMISSION: '/setting/workflow-setting/permission',
  WORKFLOW_EMAIL: '/setting/workflow-setting/email',

  RATE_CARD_SETTING: '/setting/delivery-setting/rate-card-setting',
  DELIVERY_DPM: '/delivery/dpm',

  BUSINESS_PLAN_SETTING: '/setting/delivery-setting/business-plan-setting',
  LABOR_RATE_SETTING: '/setting/delivery-setting/labor-rate-setting',
  WARNING_NORMS_SETTING: '/setting/delivery-setting/warning-norm-setting',
  ALLOCATION_VALIDATION_SETTING:
    '/setting/delivery-setting/allocation-validation-setting',

  // MVV Project Bonus
  MVV_PROJECT_BONUS_SETTING: '/setting/delivery-setting/mvv-project-bonus',
  PERFORMANCE_BONUS_SETTING:
    '/setting/delivery-setting/performance-bonus-setting',

  PERFORMANCE_RATE: '/setting/delivery-setting/performance-rate',

  // SYNC POA DATA
  SYNC_POA_USER_DATA: '/setting/system-support/sync-poa-data',

  // Activate Backdate allocation
  ACTIVATE_BACKDATE_ALLOCATION:
    '/setting/delivery-setting/activate-backdate-allocation',
}
