// CMPlan Mock Data — comprehensive dataset for all CMPlan entities
// Follows the DB schema defined in cmplan-database-design.md

// ── CI Classes ───────────────────────────────────────────────────────────────
export const MOCK_CI_CLASSES = [
  {
    id: 'class-001',
    name: 'server',
    label: 'Server',
    icon: 'hdd',
    color: '#1890ff',
    description: 'Physical or virtual server hardware.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'class-002',
    name: 'database',
    label: 'Database',
    icon: 'database',
    color: '#722ed1',
    description: 'Database instances and clusters.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'class-003',
    name: 'application',
    label: 'Application',
    icon: 'appstore',
    color: '#13c2c2',
    description: 'Software applications and services.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'class-004',
    name: 'network_device',
    label: 'Network Device',
    icon: 'cluster',
    color: '#fa8c16',
    description: 'Routers, switches, firewalls, load balancers.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'class-005',
    name: 'cloud_service',
    label: 'Cloud Service',
    icon: 'cloud',
    color: '#52c41a',
    description: 'Cloud-hosted services (AWS, Azure, GCP).',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'class-006',
    name: 'virtual_machine',
    label: 'Virtual Machine',
    icon: 'desktop',
    color: '#eb2f96',
    description: 'Virtual machines on hypervisors.',
    sortOrder: 6,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'class-007',
    name: 'storage',
    label: 'Storage',
    icon: 'save',
    color: '#a0d911',
    description: 'Storage arrays, NAS, SAN, object stores.',
    sortOrder: 7,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'class-008',
    name: 'middleware',
    label: 'Middleware',
    icon: 'api',
    color: '#096dd9',
    description: 'Message queues, ESBs, API gateways.',
    sortOrder: 8,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
]

// ── Attribute Definitions ─────────────────────────────────────────────────────
// ciClassId: null = global (applies to all classes)
export const MOCK_ATTRIBUTE_DEFINITIONS = [
  // ── Global attributes ────────────────────────────────────────────────────
  {
    id: 'attr-g-001',
    ciClassId: null,
    name: 'owner_email',
    label: 'Owner Email',
    type: 'email',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'owner@company.com',
    description: 'Primary owner responsible for this CI.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'attr-g-002',
    ciClassId: null,
    name: 'support_team',
    label: 'Support Team',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. Platform Engineering',
    description: 'Team responsible for support and maintenance.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'attr-g-003',
    ciClassId: null,
    name: 'lifecycle_phase',
    label: 'Lifecycle Phase',
    type: 'select',
    isRequired: false,
    defaultValue: 'operate',
    options: [
      { label: 'Plan', value: 'plan' },
      { label: 'Build', value: 'build' },
      { label: 'Operate', value: 'operate' },
      { label: 'Retire', value: 'retire' },
    ],
    placeholder: 'Select phase',
    description: 'Current ITIL lifecycle phase.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'attr-g-004',
    ciClassId: null,
    name: 'sla_tier',
    label: 'SLA Tier',
    type: 'select',
    isRequired: false,
    defaultValue: 'standard',
    options: [
      { label: 'Platinum (99.99%)', value: 'platinum' },
      { label: 'Gold (99.9%)', value: 'gold' },
      { label: 'Silver (99.5%)', value: 'silver' },
      { label: 'Standard (99%)', value: 'standard' },
    ],
    placeholder: 'Select SLA tier',
    description: 'Service Level Agreement tier.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'attr-g-005',
    ciClassId: null,
    name: 'cost_center',
    label: 'Cost Center',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. CC-1042',
    description: 'Finance cost center code.',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },

  // ── Server attributes ────────────────────────────────────────────────────
  {
    id: 'attr-s-001',
    ciClassId: 'class-001',
    name: 'hostname',
    label: 'Hostname',
    type: 'text',
    isRequired: true,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. prod-web-01',
    description: 'Fully qualified hostname.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-002',
    ciClassId: 'class-001',
    name: 'ip_address',
    label: 'IP Address',
    type: 'ip_address',
    isRequired: true,
    defaultValue: '',
    options: null,
    placeholder: '192.168.1.1',
    description: 'Primary IPv4 address.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-003',
    ciClassId: 'class-001',
    name: 'os_type',
    label: 'OS Type',
    type: 'select',
    isRequired: true,
    defaultValue: 'linux',
    options: [
      { label: 'Linux', value: 'linux' },
      { label: 'Windows Server', value: 'windows_server' },
      { label: 'macOS', value: 'macos' },
      { label: 'FreeBSD', value: 'freebsd' },
    ],
    placeholder: 'Select OS',
    description: 'Operating system type.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-004',
    ciClassId: 'class-001',
    name: 'os_version',
    label: 'OS Version',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. Ubuntu 22.04 LTS',
    description: 'Specific OS version/distribution.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-005',
    ciClassId: 'class-001',
    name: 'cpu_cores',
    label: 'CPU Cores',
    type: 'number',
    isRequired: false,
    defaultValue: '4',
    options: null,
    placeholder: '4',
    description: 'Total number of vCPU / CPU cores.',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-006',
    ciClassId: 'class-001',
    name: 'ram_gb',
    label: 'RAM (GB)',
    type: 'number',
    isRequired: false,
    defaultValue: '8',
    options: null,
    placeholder: '8',
    description: 'Total RAM in gigabytes.',
    sortOrder: 6,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-007',
    ciClassId: 'class-001',
    name: 'managed_by',
    label: 'Managed By',
    type: 'select',
    isRequired: false,
    defaultValue: 'manual',
    options: [
      { label: 'Ansible', value: 'ansible' },
      { label: 'Terraform', value: 'terraform' },
      { label: 'Chef', value: 'chef' },
      { label: 'Puppet', value: 'puppet' },
      { label: 'Manual', value: 'manual' },
    ],
    placeholder: 'Select tool',
    description: 'Configuration management tool.',
    sortOrder: 7,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-008',
    ciClassId: 'class-001',
    name: 'is_virtualized',
    label: 'Virtualized',
    type: 'checkbox',
    isRequired: false,
    defaultValue: 'false',
    options: null,
    placeholder: '',
    description: 'Is this server running on a hypervisor?',
    sortOrder: 8,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },

  // ── Database attributes ──────────────────────────────────────────────────
  {
    id: 'attr-d-001',
    ciClassId: 'class-002',
    name: 'db_type',
    label: 'Database Type',
    type: 'select',
    isRequired: true,
    defaultValue: '',
    options: [
      { label: 'PostgreSQL', value: 'postgresql' },
      { label: 'MySQL / MariaDB', value: 'mysql' },
      { label: 'Microsoft SQL Server', value: 'mssql' },
      { label: 'Oracle', value: 'oracle' },
      { label: 'MongoDB', value: 'mongodb' },
      { label: 'Redis', value: 'redis' },
      { label: 'Elasticsearch', value: 'elasticsearch' },
      { label: 'Cassandra', value: 'cassandra' },
    ],
    placeholder: 'Select DB type',
    description: 'Database engine.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-002',
    ciClassId: 'class-002',
    name: 'db_version',
    label: 'DB Version',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. 15.2',
    description: 'Database engine version.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-003',
    ciClassId: 'class-002',
    name: 'host_server',
    label: 'Host Server',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. db-srv-01.internal',
    description: 'Server or hostname running the database.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-004',
    ciClassId: 'class-002',
    name: 'port',
    label: 'Port',
    type: 'number',
    isRequired: false,
    defaultValue: '5432',
    options: null,
    placeholder: '5432',
    description: 'TCP port the database listens on.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-005',
    ciClassId: 'class-002',
    name: 'schema_count',
    label: 'Schema Count',
    type: 'number',
    isRequired: false,
    defaultValue: '1',
    options: null,
    placeholder: '1',
    description: 'Number of schemas / databases hosted.',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-006',
    ciClassId: 'class-002',
    name: 'backup_schedule',
    label: 'Backup Schedule',
    type: 'select',
    isRequired: false,
    defaultValue: 'daily',
    options: [
      { label: 'Hourly', value: 'hourly' },
      { label: 'Daily', value: 'daily' },
      { label: 'Weekly', value: 'weekly' },
      { label: 'None', value: 'none' },
    ],
    placeholder: 'Select schedule',
    description: 'Automated backup frequency.',
    sortOrder: 6,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },

  // ── Application attributes ───────────────────────────────────────────────
  {
    id: 'attr-a-001',
    ciClassId: 'class-003',
    name: 'app_version',
    label: 'App Version',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. 2.4.1',
    description: 'Current deployed version tag.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'attr-a-002',
    ciClassId: 'class-003',
    name: 'tech_stack',
    label: 'Tech Stack',
    type: 'multiselect',
    isRequired: false,
    defaultValue: '',
    options: [
      { label: 'React', value: 'react' },
      { label: 'Angular', value: 'angular' },
      { label: 'Vue', value: 'vue' },
      { label: 'Node.js', value: 'nodejs' },
      { label: 'Spring Boot', value: 'spring_boot' },
      { label: '.NET', value: 'dotnet' },
      { label: 'Python / FastAPI', value: 'python_fastapi' },
      { label: 'Python / Django', value: 'python_django' },
      { label: 'Go', value: 'go' },
      { label: 'Java', value: 'java' },
    ],
    placeholder: 'Select technologies',
    description: 'Technology stack used by this application.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'attr-a-003',
    ciClassId: 'class-003',
    name: 'deployment_type',
    label: 'Deployment Type',
    type: 'select',
    isRequired: false,
    defaultValue: 'container',
    options: [
      { label: 'Container (Docker/K8s)', value: 'container' },
      { label: 'Serverless', value: 'serverless' },
      { label: 'VM / Bare Metal', value: 'vm' },
      { label: 'PaaS', value: 'paas' },
      { label: 'SaaS (Third-party)', value: 'saas' },
    ],
    placeholder: 'Select deployment',
    description: 'How this application is deployed.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'attr-a-004',
    ciClassId: 'class-003',
    name: 'repository_url',
    label: 'Repository URL',
    type: 'url',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'https://github.com/org/repo',
    description: 'Source code repository.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'attr-a-005',
    ciClassId: 'class-003',
    name: 'dev_team',
    label: 'Development Team',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. Platform Team',
    description: 'Team that develops this application.',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },

  // ── Cloud Service attributes ─────────────────────────────────────────────
  {
    id: 'attr-c-001',
    ciClassId: 'class-005',
    name: 'cloud_provider',
    label: 'Cloud Provider',
    type: 'select',
    isRequired: true,
    defaultValue: 'aws',
    options: [
      { label: 'AWS', value: 'aws' },
      { label: 'Azure', value: 'azure' },
      { label: 'Google Cloud', value: 'gcp' },
      { label: 'Alibaba Cloud', value: 'alicloud' },
      { label: 'Other', value: 'other' },
    ],
    placeholder: 'Select provider',
    description: 'Cloud provider.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
  },
  {
    id: 'attr-c-002',
    ciClassId: 'class-005',
    name: 'region',
    label: 'Region',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. ap-southeast-1',
    description: 'Cloud region / availability zone.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
  },
  {
    id: 'attr-c-003',
    ciClassId: 'class-005',
    name: 'account_id',
    label: 'Account / Subscription ID',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: '123456789012',
    description: 'Cloud account or subscription identifier.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
  },
  {
    id: 'attr-c-004',
    ciClassId: 'class-005',
    name: 'monthly_cost_usd',
    label: 'Est. Monthly Cost (USD)',
    type: 'number',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: '0',
    description: 'Estimated monthly cost in USD.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
  },
]

// ── Configuration Items ───────────────────────────────────────────────────────
export const MOCK_CONFIGURATION_ITEMS = [
  {
    id: 'ci-001',
    ciClassId: 'class-001',
    name: 'prod-web-01',
    shortDescription: 'Production web server (primary)',
    status: 'active',
    criticality: 'critical',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A3',
    environment: 'production',
    tags: ['web', 'nginx', 'frontend'],
    attributes: {
      hostname: 'prod-web-01.internal',
      ip_address: '10.0.1.10',
      os_type: 'linux',
      os_version: 'Ubuntu 22.04 LTS',
      cpu_cores: 16,
      ram_gb: 32,
      managed_by: 'ansible',
      is_virtualized: false,
      owner_email: 'nguyenvana@company.com',
      support_team: 'Platform Engineering',
      lifecycle_phase: 'operate',
      sla_tier: 'platinum',
      cost_center: 'CC-1001',
    },
    complianceStatus: 'compliant',
    complianceScore: 95,
    createdBy: 'admin',
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2026-01-15T10:30:00Z',
  },
  {
    id: 'ci-002',
    ciClassId: 'class-001',
    name: 'prod-web-02',
    shortDescription: 'Production web server (secondary, load balanced)',
    status: 'active',
    criticality: 'critical',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A4',
    environment: 'production',
    tags: ['web', 'nginx', 'frontend'],
    attributes: {
      hostname: 'prod-web-02.internal',
      ip_address: '10.0.1.11',
      os_type: 'linux',
      os_version: 'Ubuntu 22.04 LTS',
      cpu_cores: 16,
      ram_gb: 32,
      managed_by: 'ansible',
      is_virtualized: false,
      owner_email: 'nguyenvana@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 90,
    createdBy: 'admin',
    createdAt: '2025-02-01T08:30:00Z',
    updatedAt: '2026-01-15T10:30:00Z',
  },
  {
    id: 'ci-003',
    ciClassId: 'class-001',
    name: 'stage-app-01',
    shortDescription: 'Staging application server',
    status: 'active',
    criticality: 'medium',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - Rack B1',
    environment: 'staging',
    tags: ['staging', 'app'],
    attributes: {
      hostname: 'stage-app-01.internal',
      ip_address: '10.1.0.5',
      os_type: 'linux',
      os_version: 'CentOS 8',
      cpu_cores: 8,
      ram_gb: 16,
      managed_by: 'terraform',
      is_virtualized: true,
      sla_tier: 'silver',
    },
    complianceStatus: 'non_compliant',
    complianceScore: 60,
    createdBy: 'trantib',
    createdAt: '2025-03-10T09:00:00Z',
    updatedAt: '2025-12-01T14:00:00Z',
  },
  {
    id: 'ci-004',
    ciClassId: 'class-002',
    name: 'prod-postgresql-01',
    shortDescription: 'Primary production PostgreSQL cluster',
    status: 'active',
    criticality: 'critical',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack B2',
    environment: 'production',
    tags: ['postgresql', 'primary', 'crm'],
    attributes: {
      db_type: 'postgresql',
      db_version: '15.3',
      host_server: 'db-srv-01.internal',
      port: 5432,
      schema_count: 8,
      backup_schedule: 'daily',
      owner_email: 'levanc@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 98,
    createdBy: 'admin',
    createdAt: '2025-02-05T08:00:00Z',
    updatedAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'ci-005',
    ciClassId: 'class-002',
    name: 'prod-redis-cache',
    shortDescription: 'Redis in-memory cache cluster for session & hot data',
    status: 'active',
    criticality: 'high',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack B3',
    environment: 'production',
    tags: ['redis', 'cache', 'session'],
    attributes: {
      db_type: 'redis',
      db_version: '7.0.12',
      host_server: 'cache-srv-01.internal',
      port: 6379,
      schema_count: 1,
      backup_schedule: 'hourly',
      sla_tier: 'gold',
    },
    complianceStatus: 'compliant',
    complianceScore: 88,
    createdBy: 'levanc',
    createdAt: '2025-04-01T10:00:00Z',
    updatedAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 'ci-006',
    ciClassId: 'class-003',
    name: 'CRM Web Portal',
    shortDescription: 'Customer Relationship Management web frontend',
    status: 'active',
    criticality: 'high',
    owner: 'Pham Thi D',
    department: 'Product',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['crm', 'react', 'frontend', 'customer-facing'],
    attributes: {
      app_version: '3.2.1',
      tech_stack: ['react', 'nodejs'],
      deployment_type: 'container',
      repository_url: 'https://github.com/company/crm-web',
      dev_team: 'CRM Squad',
      owner_email: 'phamthid@company.com',
      sla_tier: 'gold',
    },
    complianceStatus: 'compliant',
    complianceScore: 92,
    createdBy: 'phamthid',
    createdAt: '2025-05-10T11:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'ci-007',
    ciClassId: 'class-003',
    name: 'Business Plan API Service',
    shortDescription: 'Backend REST API for Business Plan module',
    status: 'active',
    criticality: 'critical',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['api', 'spring-boot', 'business-plan'],
    attributes: {
      app_version: '1.8.0',
      tech_stack: ['spring_boot', 'java'],
      deployment_type: 'container',
      repository_url: 'https://github.com/company/bp-api',
      dev_team: 'Platform Team',
      owner_email: 'hoangvane@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 97,
    createdBy: 'hoangvane',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2026-04-01T07:00:00Z',
  },
  {
    id: 'ci-008',
    ciClassId: 'class-003',
    name: 'CMPlan API Service',
    shortDescription: 'Backend for CMPlan CMDB module',
    status: 'pending',
    criticality: 'medium',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'Cloud - AWS',
    environment: 'development',
    tags: ['api', 'cmdb', 'cmplan'],
    attributes: {
      app_version: '0.1.0-alpha',
      tech_stack: ['nodejs', 'python_fastapi'],
      deployment_type: 'container',
      repository_url: 'https://github.com/company/cmplan-api',
      dev_team: 'Platform Team',
      sla_tier: 'standard',
    },
    complianceStatus: 'unknown',
    complianceScore: null,
    createdBy: 'hoangvane',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 'ci-009',
    ciClassId: 'class-004',
    name: 'Core Switch DC1',
    shortDescription: 'Cisco Nexus core switch, DC1 spine',
    status: 'active',
    criticality: 'critical',
    owner: 'Vu Thi F',
    department: 'Network Operations',
    location: 'DC1 - Rack NET-01',
    environment: 'production',
    tags: ['cisco', 'nexus', 'core-switch', 'dc1'],
    attributes: {
      owner_email: 'vuthif@company.com',
      sla_tier: 'platinum',
      lifecycle_phase: 'operate',
    },
    complianceStatus: 'compliant',
    complianceScore: 100,
    createdBy: 'admin',
    createdAt: '2024-12-01T08:00:00Z',
    updatedAt: '2025-10-01T08:00:00Z',
  },
  {
    id: 'ci-010',
    ciClassId: 'class-005',
    name: 'AWS S3 - Media Storage',
    shortDescription: 'S3 bucket for user-uploaded media and assets',
    status: 'active',
    criticality: 'medium',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'AWS ap-southeast-1',
    environment: 'production',
    tags: ['s3', 'aws', 'storage', 'media'],
    attributes: {
      cloud_provider: 'aws',
      region: 'ap-southeast-1',
      account_id: '123456789012',
      monthly_cost_usd: 340,
      owner_email: 'levanc@company.com',
      sla_tier: 'gold',
    },
    complianceStatus: 'compliant',
    complianceScore: 85,
    createdBy: 'levanc',
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2026-03-15T08:00:00Z',
  },
  {
    id: 'ci-011',
    ciClassId: 'class-005',
    name: 'Azure AKS Cluster - Prod',
    shortDescription: 'Production Kubernetes cluster on Azure AKS',
    status: 'active',
    criticality: 'critical',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'Azure Southeast Asia',
    environment: 'production',
    tags: ['kubernetes', 'aks', 'azure', 'container-orchestration'],
    attributes: {
      cloud_provider: 'azure',
      region: 'southeastasia',
      account_id: 'sub-abc-def-001',
      monthly_cost_usd: 2800,
      owner_email: 'hoangvane@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 96,
    createdBy: 'hoangvane',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'ci-012',
    ciClassId: 'class-006',
    name: 'VM-worker-01',
    shortDescription: 'Worker VM for batch processing jobs',
    status: 'maintenance',
    criticality: 'low',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - VMware',
    environment: 'production',
    tags: ['vm', 'batch', 'worker'],
    attributes: {
      owner_email: 'trantib@company.com',
      sla_tier: 'standard',
      lifecycle_phase: 'operate',
    },
    complianceStatus: 'non_compliant',
    complianceScore: 45,
    createdBy: 'trantib',
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2026-02-20T08:00:00Z',
  },
  {
    id: 'ci-013',
    ciClassId: 'class-007',
    name: 'NetApp FAS - Primary SAN',
    shortDescription: 'NetApp FAS8700 primary SAN storage array',
    status: 'active',
    criticality: 'critical',
    owner: 'Vu Thi F',
    department: 'Network Operations',
    location: 'DC1 - Storage Bay',
    environment: 'production',
    tags: ['netapp', 'san', 'storage'],
    attributes: {
      owner_email: 'vuthif@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 100,
    createdBy: 'admin',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2025-11-01T08:00:00Z',
  },
  {
    id: 'ci-014',
    ciClassId: 'class-008',
    name: 'RabbitMQ Cluster',
    shortDescription: 'Message broker for async event processing',
    status: 'active',
    criticality: 'high',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1',
    environment: 'production',
    tags: ['rabbitmq', 'message-queue', 'async'],
    attributes: {
      owner_email: 'nguyenvana@company.com',
      sla_tier: 'gold',
    },
    complianceStatus: 'compliant',
    complianceScore: 80,
    createdBy: 'nguyenvana',
    createdAt: '2025-08-01T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ci-015',
    ciClassId: 'class-002',
    name: 'dev-mongodb-01',
    shortDescription: 'Development MongoDB instance',
    status: 'inactive',
    criticality: 'low',
    owner: 'Pham Thi D',
    department: 'Product',
    location: 'DC2',
    environment: 'development',
    tags: ['mongodb', 'dev', 'nosql'],
    attributes: {
      db_type: 'mongodb',
      db_version: '6.0',
      host_server: 'dev-srv-03.internal',
      port: 27017,
      schema_count: 3,
      backup_schedule: 'none',
      sla_tier: 'standard',
    },
    complianceStatus: 'non_compliant',
    complianceScore: 30,
    createdBy: 'phamthid',
    createdAt: '2025-09-15T08:00:00Z',
    updatedAt: '2025-11-01T08:00:00Z',
  },
]

// ── CI Relationships ──────────────────────────────────────────────────────────
export const MOCK_CI_RELATIONSHIPS = [
  {
    id: 'rel-001',
    sourceId: 'ci-006',
    targetId: 'ci-007',
    relationshipType: 'depends_on',
    description: 'CRM Portal calls Business Plan API',
    expiredDate: '2026-05-14T00:00:00Z',
    createdBy: 'admin',
    createdAt: '2025-05-11T08:00:00Z',
  },
  {
    id: 'rel-002',
    sourceId: 'ci-007',
    targetId: 'ci-004',
    relationshipType: 'depends_on',
    description: 'Business Plan API reads/writes to main PostgreSQL',
    expiredDate: '2026-05-14T00:00:00Z',
    createdBy: 'admin',
    createdAt: '2025-02-06T08:00:00Z',
  },
  {
    id: 'rel-003',
    sourceId: 'ci-007',
    targetId: 'ci-005',
    relationshipType: 'uses',
    description: 'API uses Redis for session caching',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-04-02T08:00:00Z',
  },
  {
    id: 'rel-004',
    sourceId: 'ci-006',
    targetId: 'ci-001',
    relationshipType: 'runs_on',
    description: 'CRM Portal served via prod-web-01',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-05-12T08:00:00Z',
  },
  {
    id: 'rel-005',
    sourceId: 'ci-007',
    targetId: 'ci-014',
    relationshipType: 'uses',
    description: 'API publishes events to RabbitMQ',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-08-02T08:00:00Z',
  },
  {
    id: 'rel-006',
    sourceId: 'ci-001',
    targetId: 'ci-009',
    relationshipType: 'connects_to',
    description: 'Web servers connect through core switch',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-02-02T08:00:00Z',
  },
  {
    id: 'rel-007',
    sourceId: 'ci-004',
    targetId: 'ci-013',
    relationshipType: 'runs_on',
    description: 'PostgreSQL data stored on NetApp SAN',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-02-07T08:00:00Z',
  },
  {
    id: 'rel-008',
    sourceId: 'ci-011',
    targetId: 'ci-006',
    relationshipType: 'hosts',
    description: 'AKS cluster hosts CRM Portal containers',
    expiredDate: '2026-12-31T00:00:00Z',
    createdBy: 'admin',
    createdAt: '2025-06-02T08:00:00Z',
  },
  {
    id: 'rel-009',
    sourceId: 'ci-011',
    targetId: 'ci-007',
    relationshipType: 'hosts',
    description: 'AKS cluster hosts Business Plan API containers',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-06-15T08:00:00Z',
  },
  {
    id: 'rel-010',
    sourceId: 'ci-011',
    targetId: 'ci-008',
    relationshipType: 'hosts',
    description: 'AKS cluster hosts CMPlan API (dev)',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2026-01-05T08:00:00Z',
  },
]

// ── CI Groups ─────────────────────────────────────────────────────────────────
export const MOCK_CI_GROUPS = [
  {
    id: 'grp-001',
    name: 'CRM Business Service',
    description: 'All CIs supporting the CRM product suite',
    groupType: 'service',
    owner: 'Pham Thi D',
    color: '#13c2c2',
    ciIds: ['ci-001', 'ci-002', 'ci-004', 'ci-005', 'ci-006', 'ci-007', 'ci-014'],
    createdAt: '2025-05-15T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'grp-002',
    name: 'Production Environment',
    description: 'All production CIs',
    groupType: 'environment',
    owner: 'Nguyen Van A',
    color: '#f5222d',
    ciIds: ['ci-001', 'ci-002', 'ci-004', 'ci-005', 'ci-006', 'ci-007', 'ci-009', 'ci-010', 'ci-011', 'ci-013', 'ci-014'],
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'grp-003',
    name: 'Platform Engineering Stack',
    description: 'Infrastructure managed by Platform Engineering',
    groupType: 'team',
    owner: 'Hoang Van E',
    color: '#1890ff',
    ciIds: ['ci-001', 'ci-002', 'ci-007', 'ci-008', 'ci-011', 'ci-014'],
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
]

// ── Compliance Policies ───────────────────────────────────────────────────────
export const MOCK_COMPLIANCE_POLICIES = [
  {
    id: 'pol-001',
    name: 'CI Must Have Owner',
    description: 'Every CI must have an owner email defined.',
    ciClassId: null,
    rules: [
      {
        id: 'rule-001',
        field: 'attributes.owner_email',
        operator: 'not_empty',
        value: null,
        message: 'Owner email is required for all CIs.',
      },
    ],
    severity: 'high',
    isActive: true,
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
  },
  {
    id: 'pol-002',
    name: 'Server Must Have OS Info',
    description: 'All server CIs must specify OS type and version.',
    ciClassId: 'class-001',
    rules: [
      {
        id: 'rule-002',
        field: 'attributes.os_type',
        operator: 'not_empty',
        value: null,
        message: 'OS Type is required for servers.',
      },
      {
        id: 'rule-003',
        field: 'attributes.hostname',
        operator: 'not_empty',
        value: null,
        message: 'Hostname is required for servers.',
      },
    ],
    severity: 'critical',
    isActive: true,
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
  },
  {
    id: 'pol-003',
    name: 'Database Must Have Backup Schedule',
    description: 'Production/staging databases must have a backup schedule defined.',
    ciClassId: 'class-002',
    rules: [
      {
        id: 'rule-004',
        field: 'attributes.backup_schedule',
        operator: 'not_empty',
        value: null,
        message: 'Backup schedule must be configured.',
      },
      {
        id: 'rule-005',
        field: 'attributes.backup_schedule',
        operator: 'not_equals',
        value: 'none',
        message: 'Backup schedule cannot be "None" for databases.',
      },
    ],
    severity: 'critical',
    isActive: true,
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2025-02-01T08:00:00Z',
  },
  {
    id: 'pol-004',
    name: 'Application Must Have Repository',
    description: 'All application CIs should link to a source repository.',
    ciClassId: 'class-003',
    rules: [
      {
        id: 'rule-006',
        field: 'attributes.repository_url',
        operator: 'not_empty',
        value: null,
        message: 'Repository URL should be provided.',
      },
    ],
    severity: 'medium',
    isActive: true,
    createdAt: '2025-03-01T08:00:00Z',
    updatedAt: '2025-03-01T08:00:00Z',
  },
]

// ── CI Audit Log ─────────────────────────────────────────────────────────────
// Actions: ci_created | ci_updated | ci_status_changed | rel_added | rel_removed
export const MOCK_CI_AUDIT_LOG = [
  // ── prod-web-01 (ci-001) ─────────────────────────────────────────
  {
    id: 'log-001', ciId: 'ci-001', action: 'ci_created', actor: 'admin',
    timestamp: '2025-01-15T09:00:00Z', meta: {},
  },
  {
    id: 'log-002', ciId: 'ci-001', action: 'ci_updated', actor: 'alice.vu',
    timestamp: '2025-03-10T14:30:00Z',
    meta: { changes: [{ field: 'owner', from: 'admin', to: 'alice.vu' }, { field: 'department', from: 'IT', to: 'Platform Engineering' }] },
  },
  {
    id: 'log-003', ciId: 'ci-001', action: 'rel_added', actor: 'admin',
    timestamp: '2025-02-02T08:00:00Z',
    meta: { relId: 'rel-006', relType: 'connects_to', peerId: 'ci-009', peerName: 'Core Switch SW-01', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-004', ciId: 'ci-001', action: 'ci_status_changed', actor: 'alice.vu',
    timestamp: '2025-09-01T07:00:00Z',
    meta: { changes: [{ field: 'status', from: 'active', to: 'maintenance' }] },
  },
  {
    id: 'log-005', ciId: 'ci-001', action: 'ci_status_changed', actor: 'alice.vu',
    timestamp: '2025-09-03T09:30:00Z',
    meta: { changes: [{ field: 'status', from: 'maintenance', to: 'active' }] },
  },
  // ── CRM Portal (ci-006) ──────────────────────────────────────────
  {
    id: 'log-010', ciId: 'ci-006', action: 'ci_created', actor: 'admin',
    timestamp: '2025-01-20T10:00:00Z', meta: {},
  },
  {
    id: 'log-011', ciId: 'ci-006', action: 'ci_status_changed', actor: 'john.doe',
    timestamp: '2025-03-15T11:20:00Z',
    meta: { changes: [{ field: 'status', from: 'active', to: 'maintenance' }] },
  },
  {
    id: 'log-012', ciId: 'ci-006', action: 'ci_status_changed', actor: 'john.doe',
    timestamp: '2025-03-16T09:00:00Z',
    meta: { changes: [{ field: 'status', from: 'maintenance', to: 'active' }] },
  },
  {
    id: 'log-013', ciId: 'ci-006', action: 'rel_added', actor: 'admin',
    timestamp: '2025-05-11T08:00:00Z',
    meta: { relId: 'rel-001', relType: 'depends_on', peerId: 'ci-007', peerName: 'Business Plan API', direction: 'outbound', expiredDate: '2026-05-14T00:00:00Z' },
  },
  {
    id: 'log-014', ciId: 'ci-006', action: 'rel_added', actor: 'admin',
    timestamp: '2025-05-12T08:00:00Z',
    meta: { relId: 'rel-004', relType: 'runs_on', peerId: 'ci-001', peerName: 'prod-web-01', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-015', ciId: 'ci-006', action: 'rel_removed', actor: 'john.doe',
    timestamp: '2025-11-20T14:45:00Z',
    meta: { relId: 'rel-old-01', relType: 'connected_to', peerId: 'ci-003', peerName: 'prod-db-02', direction: 'outbound' },
  },
  {
    id: 'log-016', ciId: 'ci-006', action: 'ci_updated', actor: 'john.doe',
    timestamp: '2025-12-01T10:00:00Z',
    meta: { changes: [{ field: 'criticality', from: 'medium', to: 'high' }] },
  },
  // ── Business Plan API (ci-007) ──────────────────────────────────
  {
    id: 'log-020', ciId: 'ci-007', action: 'ci_created', actor: 'admin',
    timestamp: '2025-01-22T10:00:00Z', meta: {},
  },
  {
    id: 'log-021', ciId: 'ci-007', action: 'ci_updated', actor: 'jane.smith',
    timestamp: '2025-04-10T15:00:00Z',
    meta: { changes: [{ field: 'criticality', from: 'medium', to: 'high' }] },
  },
  {
    id: 'log-022', ciId: 'ci-007', action: 'rel_added', actor: 'admin',
    timestamp: '2025-02-06T08:00:00Z',
    meta: { relId: 'rel-002', relType: 'depends_on', peerId: 'ci-004', peerName: 'PostgreSQL Main', direction: 'outbound', expiredDate: '2026-05-14T00:00:00Z' },
  },
  {
    id: 'log-023', ciId: 'ci-007', action: 'rel_added', actor: 'admin',
    timestamp: '2025-04-02T08:00:00Z',
    meta: { relId: 'rel-003', relType: 'uses', peerId: 'ci-005', peerName: 'Redis Cache-01', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-024', ciId: 'ci-007', action: 'rel_added', actor: 'admin',
    timestamp: '2025-08-02T08:00:00Z',
    meta: { relId: 'rel-005', relType: 'uses', peerId: 'ci-014', peerName: 'RabbitMQ Cluster', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-025', ciId: 'ci-007', action: 'rel_removed', actor: 'jane.smith',
    timestamp: '2026-01-10T09:15:00Z',
    meta: { relId: 'rel-old-02', relType: 'connected_to', peerId: 'ci-002', peerName: 'prod-web-02', direction: 'inbound' },
  },
  // ── prod-web-01 (ci-001) — attribute & class updates ───────────────────────────────
  {
    id: 'log-030', ciId: 'ci-001', action: 'ci_attr_updated', actor: 'alice.vu',
    timestamp: '2025-06-15T11:00:00Z',
    meta: {
      classLabel: 'Server',
      changes: [
        { field: 'ip_address', label: 'IP Address', from: '10.0.10.10', to: '10.0.10.15' },
        { field: 'os_version', label: 'OS Version', from: 'Ubuntu 20.04 LTS', to: 'Ubuntu 22.04 LTS' },
      ],
    },
  },
  {
    id: 'log-031', ciId: 'ci-001', action: 'ci_attr_updated', actor: 'alice.vu',
    timestamp: '2025-10-20T09:30:00Z',
    meta: {
      classLabel: 'Server',
      changes: [
        { field: 'cpu_cores', label: 'CPU Cores', from: 4, to: 8 },
        { field: 'ram_gb', label: 'RAM (GB)', from: 16, to: 32 },
      ],
    },
  },
  {
    id: 'log-032', ciId: 'ci-001', action: 'rel_updated', actor: 'alice.vu',
    timestamp: '2026-02-14T14:00:00Z',
    meta: { relId: 'rel-004', relType: 'runs_on', peerId: 'ci-006', peerName: 'CRM Portal', direction: 'inbound', changes: [{ field: 'expiredDate', from: null, to: '2026-12-31T00:00:00Z' }] },
  },
  // ── CRM Portal (ci-006) — attr + class change ──────────────────────────────────
  {
    id: 'log-033', ciId: 'ci-006', action: 'ci_attr_updated', actor: 'john.doe',
    timestamp: '2025-07-01T10:00:00Z',
    meta: {
      classLabel: 'Application',
      changes: [
        { field: 'tech_stack', label: 'Tech Stack', from: 'React 17', to: 'React 18 + Vite' },
        { field: 'sla_tier', label: 'SLA Tier', from: 'standard', to: 'gold' },
      ],
    },
  },
  {
    id: 'log-034', ciId: 'ci-006', action: 'ci_class_changed', actor: 'admin',
    timestamp: '2025-08-10T08:30:00Z',
    meta: { fromClassId: 'class-002', fromClassName: 'Application', toClassId: 'class-002', toClassName: 'Web Application' },
  },
  // ── Business Plan API (ci-007) — attr updates ─────────────────────────────────
  {
    id: 'log-035', ciId: 'ci-007', action: 'ci_attr_updated', actor: 'jane.smith',
    timestamp: '2025-09-05T16:20:00Z',
    meta: {
      classLabel: 'Application',
      changes: [
        { field: 'api_version', label: 'API Version', from: 'v1.3.0', to: 'v1.4.0' },
        { field: 'sla_tier', label: 'SLA Tier', from: 'gold', to: 'platinum' },
      ],
    },
  },
  {
    id: 'log-036', ciId: 'ci-007', action: 'rel_updated', actor: 'jane.smith',
    timestamp: '2026-03-01T10:00:00Z',
    meta: { relId: 'rel-002', relType: 'depends_on', peerId: 'ci-004', peerName: 'PostgreSQL Main', direction: 'outbound', changes: [{ field: 'expiredDate', from: '2026-05-14T00:00:00Z', to: '2027-05-14T00:00:00Z' }] },
  },
  // ── Azure AKS Cluster - Prod (ci-011) ─────────────────────────────────
  {
    id: 'log-040', ciId: 'ci-011', action: 'ci_created', actor: 'hoangvane',
    timestamp: '2025-06-01T08:00:00Z', meta: {},
  },
  {
    id: 'log-041', ciId: 'ci-011', action: 'ci_updated', actor: 'hoangvane',
    timestamp: '2025-08-15T10:00:00Z',
    meta: { changes: [{ field: 'owner', from: 'admin', to: 'Hoang Van E' }, { field: 'department', from: 'IT', to: 'Platform Engineering' }] },
  },
  {
    id: 'log-042', ciId: 'ci-011', action: 'ci_attr_updated', actor: 'hoangvane',
    timestamp: '2025-10-01T09:00:00Z',
    meta: {
      classLabel: 'Cloud Service',
      changes: [
        { field: 'monthly_cost_usd', label: 'Monthly Cost (USD)', from: 2400, to: 2800 },
        { field: 'account_id', label: 'Account ID', from: 'sub-abc-000', to: 'sub-abc-def-001' },
      ],
    },
  },
  {
    id: 'log-043', ciId: 'ci-011', action: 'rel_added', actor: 'admin',
    timestamp: '2025-06-02T08:00:00Z',
    meta: { relId: 'rel-008', relType: 'hosts', peerId: 'ci-006', peerName: 'CRM Web Portal', direction: 'outbound', expiredDate: '2026-12-31T00:00:00Z' },
  },
  {
    id: 'log-044', ciId: 'ci-011', action: 'rel_added', actor: 'admin',
    timestamp: '2025-06-15T08:00:00Z',
    meta: { relId: 'rel-009', relType: 'hosts', peerId: 'ci-007', peerName: 'Business Plan API Service', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-045', ciId: 'ci-011', action: 'rel_added', actor: 'admin',
    timestamp: '2026-01-05T08:00:00Z',
    meta: { relId: 'rel-010', relType: 'hosts', peerId: 'ci-008', peerName: 'CMPlan API Service', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-046', ciId: 'ci-011', action: 'ci_status_changed', actor: 'hoangvane',
    timestamp: '2026-03-20T14:00:00Z',
    meta: { changes: [{ field: 'status', from: 'active', to: 'maintenance' }] },
  },
  {
    id: 'log-047', ciId: 'ci-011', action: 'ci_status_changed', actor: 'hoangvane',
    timestamp: '2026-03-21T09:30:00Z',
    meta: { changes: [{ field: 'status', from: 'maintenance', to: 'active' }] },
  },
  // ── prod-postgresql-01 (ci-004) ────────────────────────────────────
  {
    id: 'log-050', ciId: 'ci-004', action: 'ci_created', actor: 'admin',
    timestamp: '2025-02-05T08:00:00Z', meta: {},
  },
  {
    id: 'log-051', ciId: 'ci-004', action: 'ci_attr_updated', actor: 'levanc',
    timestamp: '2025-09-10T11:00:00Z',
    meta: {
      classLabel: 'Database',
      changes: [{ field: 'db_version', label: 'DB Version', from: '14.8', to: '15.3' }],
    },
  },
  {
    id: 'log-052', ciId: 'ci-004', action: 'rel_added', actor: 'admin',
    timestamp: '2025-02-07T08:00:00Z',
    meta: { relId: 'rel-007', relType: 'runs_on', peerId: 'ci-013', peerName: 'NetApp FAS - Primary SAN', direction: 'outbound', expiredDate: null },
  },
]
