// CMPlan Mock Data — comprehensive dataset for all CMPlan entities
// Follows the DB schema defined in cmplan-database-design.md

// ── CI Classes ───────────────────────────────────────────────────────────────
export const MOCK_CI_TYPES = [
  {
    id: 'type-001',
    name: 'server',
    label: 'Server',
    icon: 'hdd',
    color: '#1890ff',
    description: 'Physical or virtual server hardware.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'type-002',
    name: 'database',
    label: 'Database',
    icon: 'database',
    color: '#722ed1',
    description: 'Database instances and clusters.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'type-003',
    name: 'application',
    label: 'Application',
    icon: 'appstore',
    color: '#13c2c2',
    description: 'Software applications and services.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'type-004',
    name: 'network_device',
    label: 'Network Device',
    icon: 'cluster',
    color: '#fa8c16',
    description: 'Routers, switches, firewalls, load balancers.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'type-005',
    name: 'cloud_service',
    label: 'Cloud Service',
    icon: 'cloud',
    color: '#52c41a',
    description: 'Cloud-hosted services (AWS, Azure, GCP).',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'type-006',
    name: 'virtual_machine',
    label: 'Virtual Machine',
    icon: 'desktop',
    color: '#eb2f96',
    description: 'Virtual machines on hypervisors.',
    sortOrder: 6,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'type-007',
    name: 'storage',
    label: 'Storage',
    icon: 'save',
    color: '#a0d911',
    description: 'Storage arrays, NAS, SAN, object stores.',
    sortOrder: 7,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'type-008',
    name: 'middleware',
    label: 'Middleware',
    icon: 'api',
    color: '#096dd9',
    description: 'Message queues, ESBs, API gateways.',
    sortOrder: 8,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
]

// ── Attribute Definitions ─────────────────────────────────────────────────────
// ciTypeId: null = global (applies to all classes)
export const MOCK_ATTRIBUTE_DEFINITIONS = [
  // ── Global attributes ────────────────────────────────────────────────────
  {
    id: 'attr-g-001',
    ciTypeId: null,
    name: 'owner_email',
    label: 'Owner Email',
    type: 'email',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'owner@company.com',
    description: 'Primary owner responsible for this CI.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'attr-g-002',
    ciTypeId: null,
    name: 'support_team',
    label: 'Support Team',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. Platform Engineering',
    description: 'Team responsible for support and maintenance.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'attr-g-003',
    ciTypeId: null,
    name: 'lifecycle_phase',
    label: 'Lifecycle Phase',
    type: 'select',
    isRequired: false,
    defaultValue: 'operate',
    options: [
      { label: 'Plan', value: 'plan' },
      { label: 'Build', value: 'build' },
      { label: 'Operate', value: 'operate' },
      { label: 'Retire', value: 'retire' },
    ],
    placeholder: 'Select phase',
    description: 'Current ITIL lifecycle phase.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'attr-g-004',
    ciTypeId: null,
    name: 'sla_tier',
    label: 'SLA Tier',
    type: 'select',
    isRequired: false,
    defaultValue: 'standard',
    options: [
      { label: 'Platinum (99.99%)', value: 'platinum' },
      { label: 'Gold (99.9%)', value: 'gold' },
      { label: 'Silver (99.5%)', value: 'silver' },
      { label: 'Standard (99%)', value: 'standard' },
    ],
    placeholder: 'Select SLA tier',
    description: 'Service Level Agreement tier.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'attr-g-005',
    ciTypeId: null,
    name: 'cost_center',
    label: 'Cost Center',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. CC-1042',
    description: 'Finance cost center code.',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },

  // ── Server attributes ────────────────────────────────────────────────────
  {
    id: 'attr-s-001',
    ciTypeId: 'server',
    name: 'hostname',
    label: 'Hostname',
    type: 'text',
    isRequired: true,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. prod-web-01',
    description: 'Fully qualified hostname.',
    sortOrder: 1,
    isActive: true,
    validationRuleId: 'cr-v-001',
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-002',
    ciTypeId: 'server',
    name: 'ip_address',
    label: 'IP Address',
    type: 'ip_address',
    isRequired: true,
    defaultValue: '',
    options: null,
    placeholder: '192.168.1.1',
    description: 'Primary IPv4 address.',
    sortOrder: 2,
    isActive: true,
    validationRuleId: 'cr-v-002',
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-003',
    ciTypeId: 'server',
    name: 'os_type',
    label: 'OS Type',
    type: 'select',
    isRequired: true,
    defaultValue: 'linux',
    options: [
      { label: 'Linux', value: 'linux' },
      { label: 'Windows Server', value: 'windows_server' },
      { label: 'macOS', value: 'macos' },
      { label: 'FreeBSD', value: 'freebsd' },
    ],
    placeholder: 'Select OS',
    description: 'Operating system type.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-004',
    ciTypeId: 'server',
    name: 'os_version',
    label: 'OS Version',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. Ubuntu 22.04 LTS',
    description: 'Specific OS version/distribution.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-005',
    ciTypeId: 'server',
    name: 'cpu_cores',
    label: 'CPU Cores',
    type: 'number',
    isRequired: false,
    defaultValue: '4',
    options: null,
    placeholder: '4',
    description: 'Total number of vCPU / CPU cores.',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-006',
    ciTypeId: 'server',
    name: 'ram_gb',
    label: 'RAM (GB)',
    type: 'number',
    isRequired: false,
    defaultValue: '8',
    options: null,
    placeholder: '8',
    description: 'Total RAM in gigabytes.',
    sortOrder: 6,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-007',
    ciTypeId: 'server',
    name: 'managed_by',
    label: 'Managed By',
    type: 'select',
    isRequired: false,
    defaultValue: 'manual',
    options: [
      { label: 'Ansible', value: 'ansible' },
      { label: 'Terraform', value: 'terraform' },
      { label: 'Chef', value: 'chef' },
      { label: 'Puppet', value: 'puppet' },
      { label: 'Manual', value: 'manual' },
    ],
    placeholder: 'Select tool',
    description: 'Configuration management tool.',
    sortOrder: 7,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'attr-s-008',
    ciTypeId: 'server',
    name: 'is_virtualized',
    label: 'Virtualized',
    type: 'checkbox',
    isRequired: false,
    defaultValue: 'false',
    options: null,
    placeholder: '',
    description: 'Is this server running on a hypervisor?',
    sortOrder: 8,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },

  // ── Database attributes ──────────────────────────────────────────────────
  {
    id: 'attr-d-001',
    ciTypeId: 'database',
    name: 'db_type',
    label: 'Database Type',
    type: 'select',
    isRequired: true,
    defaultValue: '',
    options: [
      { label: 'PostgreSQL', value: 'postgresql' },
      { label: 'MySQL / MariaDB', value: 'mysql' },
      { label: 'Microsoft SQL Server', value: 'mssql' },
      { label: 'Oracle', value: 'oracle' },
      { label: 'MongoDB', value: 'mongodb' },
      { label: 'Redis', value: 'redis' },
      { label: 'Elasticsearch', value: 'elasticsearch' },
      { label: 'Cassandra', value: 'cassandra' },
    ],
    placeholder: 'Select DB type',
    description: 'Database engine.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-002',
    ciTypeId: 'database',
    name: 'db_version',
    label: 'DB Version',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. 15.2',
    description: 'Database engine version.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-003',
    ciTypeId: 'database',
    name: 'host_server',
    label: 'Host Server',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. db-srv-01.internal',
    description: 'Server or hostname running the database.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-004',
    ciTypeId: 'database',
    name: 'port',
    label: 'Port',
    type: 'number',
    isRequired: false,
    defaultValue: '5432',
    options: null,
    placeholder: '5432',
    description: 'TCP port the database listens on.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-005',
    ciTypeId: 'database',
    name: 'schema_count',
    label: 'Schema Count',
    type: 'number',
    isRequired: false,
    defaultValue: '1',
    options: null,
    placeholder: '1',
    description: 'Number of schemas / databases hosted.',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'attr-d-006',
    ciTypeId: 'database',
    name: 'backup_schedule',
    label: 'Backup Schedule',
    type: 'select',
    isRequired: false,
    defaultValue: 'daily',
    options: [
      { label: 'Hourly', value: 'hourly' },
      { label: 'Daily', value: 'daily' },
      { label: 'Weekly', value: 'weekly' },
      { label: 'None', value: 'none' },
    ],
    placeholder: 'Select schedule',
    description: 'Automated backup frequency.',
    sortOrder: 6,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },

  // ── Application attributes ───────────────────────────────────────────────
  {
    id: 'attr-a-001',
    ciTypeId: 'application',
    name: 'app_version',
    label: 'App Version',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. 2.4.1',
    description: 'Current deployed version tag.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'attr-a-002',
    ciTypeId: 'application',
    name: 'tech_stack',
    label: 'Tech Stack',
    type: 'multiselect',
    isRequired: false,
    defaultValue: '',
    options: [
      { label: 'React', value: 'react' },
      { label: 'Angular', value: 'angular' },
      { label: 'Vue', value: 'vue' },
      { label: 'Node.js', value: 'nodejs' },
      { label: 'Spring Boot', value: 'spring_boot' },
      { label: '.NET', value: 'dotnet' },
      { label: 'Python / FastAPI', value: 'python_fastapi' },
      { label: 'Python / Django', value: 'python_django' },
      { label: 'Go', value: 'go' },
      { label: 'Java', value: 'java' },
    ],
    placeholder: 'Select technologies',
    description: 'Technology stack used by this application.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'attr-a-003',
    ciTypeId: 'application',
    name: 'deployment_type',
    label: 'Deployment Type',
    type: 'select',
    isRequired: false,
    defaultValue: 'container',
    options: [
      { label: 'Container (Docker/K8s)', value: 'container' },
      { label: 'Serverless', value: 'serverless' },
      { label: 'VM / Bare Metal', value: 'vm' },
      { label: 'PaaS', value: 'paas' },
      { label: 'SaaS (Third-party)', value: 'saas' },
    ],
    placeholder: 'Select deployment',
    description: 'How this application is deployed.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'attr-a-004',
    ciTypeId: 'application',
    name: 'repository_url',
    label: 'Repository URL',
    type: 'url',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'https://github.com/org/repo',
    description: 'Source code repository.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'attr-a-005',
    ciTypeId: 'application',
    name: 'dev_team',
    label: 'Development Team',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. Platform Team',
    description: 'Team that develops this application.',
    sortOrder: 5,
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },

  // ── Cloud Service attributes ─────────────────────────────────────────────
  {
    id: 'attr-c-001',
    ciTypeId: 'cloud_service',
    name: 'cloud_provider',
    label: 'Cloud Provider',
    type: 'select',
    isRequired: true,
    defaultValue: 'aws',
    options: [
      { label: 'AWS', value: 'aws' },
      { label: 'Azure', value: 'azure' },
      { label: 'Google Cloud', value: 'gcp' },
      { label: 'Alibaba Cloud', value: 'alicloud' },
      { label: 'Other', value: 'other' },
    ],
    placeholder: 'Select provider',
    description: 'Cloud provider.',
    sortOrder: 1,
    isActive: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
  },
  {
    id: 'attr-c-002',
    ciTypeId: 'cloud_service',
    name: 'region',
    label: 'Region',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: 'e.g. ap-southeast-1',
    description: 'Cloud region / availability zone.',
    sortOrder: 2,
    isActive: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
  },
  {
    id: 'attr-c-003',
    ciTypeId: 'cloud_service',
    name: 'account_id',
    label: 'Account / Subscription ID',
    type: 'text',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: '123456789012',
    description: 'Cloud account or subscription identifier.',
    sortOrder: 3,
    isActive: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
  },
  {
    id: 'attr-c-004',
    ciTypeId: 'cloud_service',
    name: 'monthly_cost_usd',
    label: 'Est. Monthly Cost (USD)',
    type: 'number',
    isRequired: false,
    defaultValue: '',
    options: null,
    placeholder: '0',
    description: 'Estimated monthly cost in USD.',
    sortOrder: 4,
    isActive: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
  },
]

// ── Configuration Items ───────────────────────────────────────────────────────
export const MOCK_CONFIGURATION_ITEMS = [
  {
    id: 'ci-001',
    ciTypeId: 'server',
    name: 'prod-web-01',
    shortDescription: 'Production web server (primary)',
    status: 'active',
    criticality: 'critical',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A3',
    environment: 'production',
    tags: ['web', 'nginx', 'frontend'],
    attributes: {
      hostname: 'prod-web-01.internal',
      ip_address: '10.0.1.10',
      os_type: 'linux',
      os_version: 'Ubuntu 22.04 LTS',
      cpu_cores: 16,
      ram_gb: 32,
      managed_by: 'ansible',
      is_virtualized: false,
      owner_email: 'nguyenvana@company.com',
      support_team: 'Platform Engineering',
      lifecycle_phase: 'operate',
      sla_tier: 'platinum',
      cost_center: 'CC-1001',
    },
    complianceStatus: 'compliant',
    complianceScore: 95,
    createdBy: 'admin',
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2026-01-15T10:30:00Z',
  },
  {
    id: 'ci-002',
    ciTypeId: 'server',
    name: 'prod-web-02',
    shortDescription: 'Production web server (secondary, load balanced)',
    status: 'active',
    criticality: 'critical',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A4',
    environment: 'production',
    tags: ['web', 'nginx', 'frontend'],
    attributes: {
      hostname: 'prod-web-02.internal',
      ip_address: '10.0.1.11',
      os_type: 'linux',
      os_version: 'Ubuntu 22.04 LTS',
      cpu_cores: 16,
      ram_gb: 32,
      managed_by: 'ansible',
      is_virtualized: false,
      owner_email: 'nguyenvana@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 90,
    createdBy: 'admin',
    createdAt: '2025-02-01T08:30:00Z',
    updatedAt: '2026-01-15T10:30:00Z',
  },
  {
    id: 'ci-003',
    ciTypeId: 'server',
    name: 'stage-app-01',
    shortDescription: 'Staging application server',
    status: 'active',
    criticality: 'medium',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - Rack B1',
    environment: 'staging',
    tags: ['staging', 'app'],
    attributes: {
      hostname: 'stage-app-01.internal',
      ip_address: '10.1.0.5',
      os_type: 'linux',
      os_version: 'CentOS 8',
      cpu_cores: 8,
      ram_gb: 16,
      managed_by: 'terraform',
      is_virtualized: true,
      sla_tier: 'silver',
    },
    complianceStatus: 'non_compliant',
    complianceScore: 60,
    createdBy: 'trantib',
    createdAt: '2025-03-10T09:00:00Z',
    updatedAt: '2025-12-01T14:00:00Z',
  },
  {
    id: 'ci-004',
    ciTypeId: 'database',
    name: 'prod-postgresql-01',
    shortDescription: 'Primary production PostgreSQL cluster',
    status: 'active',
    criticality: 'critical',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack B2',
    environment: 'production',
    tags: ['postgresql', 'primary', 'crm'],
    attributes: {
      db_type: 'postgresql',
      db_version: '15.3',
      host_server: 'db-srv-01.internal',
      port: 5432,
      schema_count: 8,
      backup_schedule: 'daily',
      owner_email: 'levanc@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 98,
    createdBy: 'admin',
    createdAt: '2025-02-05T08:00:00Z',
    updatedAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'ci-005',
    ciTypeId: 'database',
    name: 'prod-redis-cache',
    shortDescription: 'Redis in-memory cache cluster for session & hot data',
    status: 'active',
    criticality: 'high',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack B3',
    environment: 'production',
    tags: ['redis', 'cache', 'session'],
    attributes: {
      db_type: 'redis',
      db_version: '7.0.12',
      host_server: 'cache-srv-01.internal',
      port: 6379,
      schema_count: 1,
      backup_schedule: 'hourly',
      sla_tier: 'gold',
    },
    complianceStatus: 'compliant',
    complianceScore: 88,
    createdBy: 'levanc',
    createdAt: '2025-04-01T10:00:00Z',
    updatedAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 'ci-006',
    ciTypeId: 'application',
    name: 'CRM Web Portal',
    shortDescription: 'Customer Relationship Management web frontend',
    status: 'active',
    criticality: 'high',
    owner: 'Pham Thi D',
    department: 'Product',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['crm', 'react', 'frontend', 'customer-facing'],
    attributes: {
      app_version: '3.2.1',
      tech_stack: ['react', 'nodejs'],
      deployment_type: 'container',
      repository_url: 'https://github.com/company/crm-web',
      dev_team: 'CRM Squad',
      owner_email: 'phamthid@company.com',
      sla_tier: 'gold',
    },
    complianceStatus: 'compliant',
    complianceScore: 92,
    createdBy: 'phamthid',
    createdAt: '2025-05-10T11:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'ci-007',
    ciTypeId: 'application',
    name: 'Business Plan API Service',
    shortDescription: 'Backend REST API for Business Plan module',
    status: 'active',
    criticality: 'critical',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['api', 'spring-boot', 'business-plan'],
    attributes: {
      app_version: '1.8.0',
      tech_stack: ['spring_boot', 'java'],
      deployment_type: 'container',
      repository_url: 'https://github.com/company/bp-api',
      dev_team: 'Platform Team',
      owner_email: 'hoangvane@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 97,
    createdBy: 'hoangvane',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2026-04-01T07:00:00Z',
  },
  {
    id: 'ci-008',
    ciTypeId: 'application',
    name: 'CMPlan API Service',
    shortDescription: 'Backend for CMPlan CMDB module',
    status: 'pending',
    criticality: 'medium',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'Cloud - AWS',
    environment: 'development',
    tags: ['api', 'cmdb', 'cmplan'],
    attributes: {
      app_version: '0.1.0-alpha',
      tech_stack: ['nodejs', 'python_fastapi'],
      deployment_type: 'container',
      repository_url: 'https://github.com/company/cmplan-api',
      dev_team: 'Platform Team',
      sla_tier: 'standard',
    },
    complianceStatus: 'unknown',
    complianceScore: null,
    createdBy: 'hoangvane',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 'ci-009',
    ciTypeId: 'network_device',
    name: 'Core Switch DC1',
    shortDescription: 'Cisco Nexus core switch, DC1 spine',
    status: 'active',
    criticality: 'critical',
    owner: 'Vu Thi F',
    department: 'Network Operations',
    location: 'DC1 - Rack NET-01',
    environment: 'production',
    tags: ['cisco', 'nexus', 'core-switch', 'dc1'],
    attributes: {
      owner_email: 'vuthif@company.com',
      sla_tier: 'platinum',
      lifecycle_phase: 'operate',
    },
    complianceStatus: 'compliant',
    complianceScore: 100,
    createdBy: 'admin',
    createdAt: '2024-12-01T08:00:00Z',
    updatedAt: '2025-10-01T08:00:00Z',
  },
  {
    id: 'ci-010',
    ciTypeId: 'cloud_service',
    name: 'AWS S3 - Media Storage',
    shortDescription: 'S3 bucket for user-uploaded media and assets',
    status: 'active',
    criticality: 'medium',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'AWS ap-southeast-1',
    environment: 'production',
    tags: ['s3', 'aws', 'storage', 'media'],
    attributes: {
      cloud_provider: 'aws',
      region: 'ap-southeast-1',
      account_id: '123456789012',
      monthly_cost_usd: 340,
      owner_email: 'levanc@company.com',
      sla_tier: 'gold',
    },
    complianceStatus: 'compliant',
    complianceScore: 85,
    createdBy: 'levanc',
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2026-03-15T08:00:00Z',
  },
  {
    id: 'ci-011',
    ciTypeId: 'cloud_service',
    name: 'Azure AKS Cluster - Prod',
    shortDescription: 'Production Kubernetes cluster on Azure AKS',
    status: 'active',
    criticality: 'critical',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'Azure Southeast Asia',
    environment: 'production',
    tags: ['kubernetes', 'aks', 'azure', 'container-orchestration'],
    attributes: {
      cloud_provider: 'azure',
      region: 'southeastasia',
      account_id: 'sub-abc-def-001',
      monthly_cost_usd: 2800,
      owner_email: 'hoangvane@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 96,
    createdBy: 'hoangvane',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'ci-012',
    ciTypeId: 'virtual_machine',
    name: 'VM-worker-01',
    shortDescription: 'Worker VM for batch processing jobs',
    status: 'maintenance',
    criticality: 'low',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - VMware',
    environment: 'production',
    tags: ['vm', 'batch', 'worker'],
    attributes: {
      owner_email: 'trantib@company.com',
      sla_tier: 'standard',
      lifecycle_phase: 'operate',
    },
    complianceStatus: 'non_compliant',
    complianceScore: 45,
    createdBy: 'trantib',
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2026-02-20T08:00:00Z',
  },
  {
    id: 'ci-013',
    ciTypeId: 'storage',
    name: 'NetApp FAS - Primary SAN',
    shortDescription: 'NetApp FAS8700 primary SAN storage array',
    status: 'active',
    criticality: 'critical',
    owner: 'Vu Thi F',
    department: 'Network Operations',
    location: 'DC1 - Storage Bay',
    environment: 'production',
    tags: ['netapp', 'san', 'storage'],
    attributes: {
      owner_email: 'vuthif@company.com',
      sla_tier: 'platinum',
    },
    complianceStatus: 'compliant',
    complianceScore: 100,
    createdBy: 'admin',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2025-11-01T08:00:00Z',
  },
  {
    id: 'ci-014',
    ciTypeId: 'middleware',
    name: 'RabbitMQ Cluster',
    shortDescription: 'Message broker for async event processing',
    status: 'active',
    criticality: 'high',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1',
    environment: 'production',
    tags: ['rabbitmq', 'message-queue', 'async'],
    attributes: {
      owner_email: 'nguyenvana@company.com',
      sla_tier: 'gold',
    },
    complianceStatus: 'compliant',
    complianceScore: 80,
    createdBy: 'nguyenvana',
    createdAt: '2025-08-01T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ci-015',
    ciTypeId: 'database',
    name: 'dev-mongodb-01',
    shortDescription: 'Development MongoDB instance',
    status: 'inactive',
    criticality: 'low',
    owner: 'Pham Thi D',
    department: 'Product',
    location: 'DC2',
    environment: 'development',
    tags: ['mongodb', 'dev', 'nosql'],
    attributes: {
      db_type: 'mongodb',
      db_version: '6.0',
      host_server: 'dev-srv-03.internal',
      port: 27017,
      schema_count: 3,
      backup_schedule: 'none',
      sla_tier: 'standard',
    },
    complianceStatus: 'non_compliant',
    complianceScore: 30,
    createdBy: 'phamthid',
    createdAt: '2025-09-15T08:00:00Z',
    updatedAt: '2025-11-01T08:00:00Z',
  },

  // ── Additional Applications ──────────────────────────────────────────────
  {
    id: 'ci-016',
    ciTypeId: 'application',
    name: 'HR Management System',
    shortDescription: 'Human Resource management web application',
    status: 'active',
    criticality: 'high',
    owner: 'Pham Thi D',
    department: 'HR',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['hr', 'react', 'internal'],
    attributes: { app_version: '2.1.0', tech_stack: ['react', 'java'], deployment_type: 'container', owner_email: 'phamthid@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 88,
    createdBy: 'phamthid',
    createdAt: '2025-03-10T08:00:00Z',
    updatedAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'ci-017',
    ciTypeId: 'application',
    name: 'Finance Portal',
    shortDescription: 'Internal finance and accounting web portal',
    status: 'active',
    criticality: 'critical',
    owner: 'Le Van C',
    department: 'Finance',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['finance', 'internal', 'accounting'],
    attributes: { app_version: '1.4.2', tech_stack: ['angular', 'dotnet'], deployment_type: 'container', owner_email: 'levanc@company.com', sla_tier: 'platinum' },
    complianceStatus: 'compliant',
    complianceScore: 94,
    createdBy: 'levanc',
    createdAt: '2025-04-15T08:00:00Z',
    updatedAt: '2026-03-10T08:00:00Z',
  },
  {
    id: 'ci-018',
    ciTypeId: 'application',
    name: 'CMPlan Web Portal',
    shortDescription: 'Frontend for the CMPlan CMDB module',
    status: 'pending',
    criticality: 'medium',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'Cloud - AWS',
    environment: 'development',
    tags: ['cmdb', 'react', 'cmplan'],
    attributes: { app_version: '0.2.0-beta', tech_stack: ['react'], deployment_type: 'container', owner_email: 'hoangvane@company.com', sla_tier: 'standard' },
    complianceStatus: 'unknown',
    complianceScore: null,
    createdBy: 'hoangvane',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-04-20T08:00:00Z',
  },
  {
    id: 'ci-019',
    ciTypeId: 'application',
    name: 'Notification Service',
    shortDescription: 'Async push/email/SMS notification microservice',
    status: 'active',
    criticality: 'high',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['notification', 'microservice', 'async'],
    attributes: { app_version: '1.1.3', tech_stack: ['nodejs'], deployment_type: 'container', owner_email: 'nguyenvana@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 91,
    createdBy: 'nguyenvana',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'ci-020',
    ciTypeId: 'application',
    name: 'Auth Service',
    shortDescription: 'Centralized authentication and authorization service (OAuth2 / JWT)',
    status: 'active',
    criticality: 'critical',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['auth', 'oauth2', 'jwt', 'security'],
    attributes: { app_version: '3.0.1', tech_stack: ['spring_boot', 'java'], deployment_type: 'container', owner_email: 'hoangvane@company.com', sla_tier: 'platinum' },
    complianceStatus: 'compliant',
    complianceScore: 99,
    createdBy: 'hoangvane',
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2026-04-05T08:00:00Z',
  },
  {
    id: 'ci-021',
    ciTypeId: 'application',
    name: 'Report Service',
    shortDescription: 'Scheduled and on-demand report generation service',
    status: 'active',
    criticality: 'medium',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['report', 'pdf', 'data'],
    attributes: { app_version: '2.0.0', tech_stack: ['python_fastapi'], deployment_type: 'container', owner_email: 'levanc@company.com', sla_tier: 'silver' },
    complianceStatus: 'compliant',
    complianceScore: 83,
    createdBy: 'levanc',
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2026-02-20T08:00:00Z',
  },
  {
    id: 'ci-022',
    ciTypeId: 'application',
    name: 'Mobile API Gateway',
    shortDescription: 'API gateway routing mobile app requests to backend services',
    status: 'active',
    criticality: 'high',
    owner: 'Pham Thi D',
    department: 'Product',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['gateway', 'mobile', 'api'],
    attributes: { app_version: '1.6.0', tech_stack: ['nodejs'], deployment_type: 'container', owner_email: 'phamthid@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 89,
    createdBy: 'phamthid',
    createdAt: '2025-08-10T08:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'ci-023',
    ciTypeId: 'application',
    name: 'Data Export Service',
    shortDescription: 'Batch data export to external systems and S3',
    status: 'active',
    criticality: 'low',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'Cloud - AWS',
    environment: 'staging',
    tags: ['export', 'batch', 's3'],
    attributes: { app_version: '1.0.4', tech_stack: ['python_fastapi'], deployment_type: 'container', owner_email: 'levanc@company.com', sla_tier: 'standard' },
    complianceStatus: 'compliant',
    complianceScore: 76,
    createdBy: 'levanc',
    createdAt: '2025-10-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'ci-024',
    ciTypeId: 'application',
    name: 'Admin Dashboard',
    shortDescription: 'Internal admin panel for platform operations',
    status: 'active',
    criticality: 'medium',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'Cloud - AWS',
    environment: 'production',
    tags: ['admin', 'internal', 'ops'],
    attributes: { app_version: '1.3.0', tech_stack: ['react', 'nodejs'], deployment_type: 'container', owner_email: 'hoangvane@company.com', sla_tier: 'silver' },
    complianceStatus: 'compliant',
    complianceScore: 85,
    createdBy: 'hoangvane',
    createdAt: '2025-05-20T08:00:00Z',
    updatedAt: '2026-02-15T08:00:00Z',
  },
  {
    id: 'ci-025',
    ciTypeId: 'application',
    name: 'Monitoring Agent',
    shortDescription: 'Lightweight agent for infrastructure metrics collection and alerting',
    status: 'active',
    criticality: 'high',
    owner: 'Vu Thi F',
    department: 'Network Operations',
    location: 'DC1',
    environment: 'production',
    tags: ['monitoring', 'metrics', 'alerting'],
    attributes: { app_version: '2.4.1', tech_stack: ['golang'], deployment_type: 'container', owner_email: 'vuthif@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 93,
    createdBy: 'admin',
    createdAt: '2025-02-15T08:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
  },

  // ── Additional Servers ───────────────────────────────────────────────────
  {
    id: 'ci-026',
    ciTypeId: 'server',
    name: 'prod-app-01',
    shortDescription: 'Primary production application server',
    status: 'active',
    criticality: 'critical',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A5',
    environment: 'production',
    tags: ['app', 'tomcat', 'backend'],
    attributes: { hostname: 'prod-app-01.internal', ip_address: '10.0.2.10', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 32, ram_gb: 64, managed_by: 'ansible', is_virtualized: false, owner_email: 'nguyenvana@company.com', sla_tier: 'platinum' },
    complianceStatus: 'compliant',
    complianceScore: 97,
    createdBy: 'admin',
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'ci-027',
    ciTypeId: 'server',
    name: 'prod-app-02',
    shortDescription: 'Secondary production application server',
    status: 'active',
    criticality: 'critical',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A6',
    environment: 'production',
    tags: ['app', 'tomcat', 'backend'],
    attributes: { hostname: 'prod-app-02.internal', ip_address: '10.0.2.11', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 32, ram_gb: 64, managed_by: 'ansible', is_virtualized: false, owner_email: 'nguyenvana@company.com', sla_tier: 'platinum' },
    complianceStatus: 'compliant',
    complianceScore: 96,
    createdBy: 'admin',
    createdAt: '2025-02-01T08:30:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'ci-028',
    ciTypeId: 'server',
    name: 'prod-db-server-01',
    shortDescription: 'Primary dedicated database server',
    status: 'active',
    criticality: 'critical',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack B4',
    environment: 'production',
    tags: ['database', 'backend'],
    attributes: { hostname: 'prod-db-01.internal', ip_address: '10.0.3.10', os_type: 'linux', os_version: 'RHEL 8', cpu_cores: 64, ram_gb: 256, managed_by: 'ansible', is_virtualized: false, owner_email: 'levanc@company.com', sla_tier: 'platinum' },
    complianceStatus: 'compliant',
    complianceScore: 100,
    createdBy: 'admin',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'ci-029',
    ciTypeId: 'server',
    name: 'prod-db-server-02',
    shortDescription: 'Secondary database server (replica / analytics)',
    status: 'active',
    criticality: 'high',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack B5',
    environment: 'production',
    tags: ['database', 'replica'],
    attributes: { hostname: 'prod-db-02.internal', ip_address: '10.0.3.11', os_type: 'linux', os_version: 'RHEL 8', cpu_cores: 32, ram_gb: 128, managed_by: 'ansible', is_virtualized: false, owner_email: 'levanc@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 95,
    createdBy: 'admin',
    createdAt: '2025-02-05T08:00:00Z',
    updatedAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'ci-030',
    ciTypeId: 'server',
    name: 'dev-app-01',
    shortDescription: 'Development application server for internal teams',
    status: 'active',
    criticality: 'low',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - Rack C1',
    environment: 'development',
    tags: ['dev', 'app'],
    attributes: { hostname: 'dev-app-01.internal', ip_address: '10.1.2.10', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 8, ram_gb: 16, managed_by: 'terraform', is_virtualized: true, owner_email: 'trantib@company.com', sla_tier: 'standard' },
    complianceStatus: 'non_compliant',
    complianceScore: 55,
    createdBy: 'trantib',
    createdAt: '2025-04-01T08:00:00Z',
    updatedAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'ci-031',
    ciTypeId: 'server',
    name: 'stage-web-01',
    shortDescription: 'Staging web server for pre-production testing',
    status: 'active',
    criticality: 'medium',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - Rack C2',
    environment: 'staging',
    tags: ['staging', 'web', 'nginx'],
    attributes: { hostname: 'stage-web-01.internal', ip_address: '10.1.1.10', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 8, ram_gb: 16, managed_by: 'terraform', is_virtualized: true, owner_email: 'trantib@company.com', sla_tier: 'silver' },
    complianceStatus: 'compliant',
    complianceScore: 72,
    createdBy: 'trantib',
    createdAt: '2025-03-15T08:00:00Z',
    updatedAt: '2025-12-10T08:00:00Z',
  },
  {
    id: 'ci-032',
    ciTypeId: 'server',
    name: 'prod-mq-server-01',
    shortDescription: 'Dedicated message queue server for middleware',
    status: 'active',
    criticality: 'high',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A7',
    environment: 'production',
    tags: ['mq', 'messaging', 'backend'],
    attributes: { hostname: 'prod-mq-01.internal', ip_address: '10.0.2.20', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 16, ram_gb: 32, managed_by: 'ansible', is_virtualized: false, owner_email: 'nguyenvana@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 90,
    createdBy: 'admin',
    createdAt: '2025-08-01T08:00:00Z',
    updatedAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'ci-033',
    ciTypeId: 'server',
    name: 'prod-backup-01',
    shortDescription: 'Dedicated backup server for prod-app-01 replication',
    status: 'active',
    criticality: 'medium',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC2 - Rack A1',
    environment: 'production',
    tags: ['backup', 'dr'],
    attributes: { hostname: 'prod-backup-01.internal', ip_address: '10.2.2.10', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 16, ram_gb: 32, managed_by: 'ansible', is_virtualized: false, owner_email: 'nguyenvana@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 87,
    createdBy: 'admin',
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2026-02-01T08:00:00Z',
  },

  // ── Additional Servers (scroll test: 14 extra → total 25 server items, 3 pages × 10) ──
  {
    id: 'ci-s-012',
    ciTypeId: 'server',
    name: 'dev-build-01',
    shortDescription: 'CI/CD build agent #1',
    status: 'active',
    criticality: 'low',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - Rack C1',
    environment: 'development',
    tags: ['ci-cd', 'jenkins'],
    attributes: { hostname: 'dev-build-01.internal', ip_address: '10.3.0.11', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 4, ram_gb: 8, managed_by: 'ansible', is_virtualized: true, sla_tier: 'bronze' },
    complianceStatus: 'compliant',
    complianceScore: 82,
    createdBy: 'admin',
    createdAt: '2025-04-01T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ci-s-013',
    ciTypeId: 'server',
    name: 'dev-build-02',
    shortDescription: 'CI/CD build agent #2',
    status: 'active',
    criticality: 'low',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - Rack C1',
    environment: 'development',
    tags: ['ci-cd', 'jenkins'],
    attributes: { hostname: 'dev-build-02.internal', ip_address: '10.3.0.12', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 4, ram_gb: 8, managed_by: 'ansible', is_virtualized: true, sla_tier: 'bronze' },
    complianceStatus: 'compliant',
    complianceScore: 80,
    createdBy: 'admin',
    createdAt: '2025-04-01T08:15:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ci-s-014',
    ciTypeId: 'server',
    name: 'prod-proxy-01',
    shortDescription: 'Production reverse proxy (HAProxy)',
    status: 'active',
    criticality: 'high',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A8',
    environment: 'production',
    tags: ['proxy', 'haproxy', 'loadbalancer'],
    attributes: { hostname: 'prod-proxy-01.internal', ip_address: '10.0.1.20', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 8, ram_gb: 16, managed_by: 'ansible', is_virtualized: false, sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 91,
    createdBy: 'admin',
    createdAt: '2025-05-01T08:00:00Z',
    updatedAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'ci-s-015',
    ciTypeId: 'server',
    name: 'prod-proxy-02',
    shortDescription: 'Production reverse proxy (HAProxy) – standby',
    status: 'active',
    criticality: 'high',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC2 - Rack A2',
    environment: 'production',
    tags: ['proxy', 'haproxy', 'dr'],
    attributes: { hostname: 'prod-proxy-02.internal', ip_address: '10.2.1.20', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 8, ram_gb: 16, managed_by: 'ansible', is_virtualized: false, sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 90,
    createdBy: 'admin',
    createdAt: '2025-05-01T08:30:00Z',
    updatedAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'ci-s-016',
    ciTypeId: 'server',
    name: 'prod-log-01',
    shortDescription: 'Centralized log aggregation server (Elasticsearch node)',
    status: 'active',
    criticality: 'medium',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack D1',
    environment: 'production',
    tags: ['logging', 'elasticsearch', 'elk'],
    attributes: { hostname: 'prod-log-01.internal', ip_address: '10.0.3.30', os_type: 'linux', os_version: 'Ubuntu 20.04 LTS', cpu_cores: 16, ram_gb: 64, managed_by: 'ansible', is_virtualized: false, sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 88,
    createdBy: 'admin',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-01-25T08:00:00Z',
  },
  {
    id: 'ci-s-017',
    ciTypeId: 'server',
    name: 'prod-log-02',
    shortDescription: 'Centralized log aggregation server (Elasticsearch node 2)',
    status: 'active',
    criticality: 'medium',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack D2',
    environment: 'production',
    tags: ['logging', 'elasticsearch', 'elk'],
    attributes: { hostname: 'prod-log-02.internal', ip_address: '10.0.3.31', os_type: 'linux', os_version: 'Ubuntu 20.04 LTS', cpu_cores: 16, ram_gb: 64, managed_by: 'ansible', is_virtualized: false, sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 87,
    createdBy: 'admin',
    createdAt: '2025-06-15T08:00:00Z',
    updatedAt: '2026-01-25T08:00:00Z',
  },
  {
    id: 'ci-s-018',
    ciTypeId: 'server',
    name: 'prod-monitor-01',
    shortDescription: 'Infrastructure monitoring server (Prometheus + Grafana)',
    status: 'active',
    criticality: 'medium',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC1 - Rack D3',
    environment: 'production',
    tags: ['monitoring', 'prometheus', 'grafana'],
    attributes: { hostname: 'prod-monitor-01.internal', ip_address: '10.0.3.40', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 8, ram_gb: 32, managed_by: 'ansible', is_virtualized: false, sla_tier: 'silver' },
    complianceStatus: 'compliant',
    complianceScore: 85,
    createdBy: 'admin',
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2026-02-05T08:00:00Z',
  },
  {
    id: 'ci-s-019',
    ciTypeId: 'server',
    name: 'stage-db-01',
    shortDescription: 'Staging database server (PostgreSQL)',
    status: 'active',
    criticality: 'low',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC2 - Rack B2',
    environment: 'staging',
    tags: ['staging', 'postgresql'],
    attributes: { hostname: 'stage-db-01.internal', ip_address: '10.1.1.10', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 4, ram_gb: 16, managed_by: 'terraform', is_virtualized: true, sla_tier: 'bronze' },
    complianceStatus: 'non_compliant',
    complianceScore: 55,
    createdBy: 'admin',
    createdAt: '2025-08-01T08:00:00Z',
    updatedAt: '2025-12-01T08:00:00Z',
  },
  {
    id: 'ci-s-020',
    ciTypeId: 'server',
    name: 'dev-k8s-node-01',
    shortDescription: 'Kubernetes worker node #1 (dev cluster)',
    status: 'active',
    criticality: 'medium',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - Rack C2',
    environment: 'development',
    tags: ['kubernetes', 'k8s', 'worker'],
    attributes: { hostname: 'dev-k8s-node-01.internal', ip_address: '10.3.1.11', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 8, ram_gb: 32, managed_by: 'kubeadm', is_virtualized: true, sla_tier: 'silver' },
    complianceStatus: 'compliant',
    complianceScore: 83,
    createdBy: 'admin',
    createdAt: '2025-09-10T08:00:00Z',
    updatedAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'ci-s-021',
    ciTypeId: 'server',
    name: 'dev-k8s-node-02',
    shortDescription: 'Kubernetes worker node #2 (dev cluster)',
    status: 'active',
    criticality: 'medium',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - Rack C3',
    environment: 'development',
    tags: ['kubernetes', 'k8s', 'worker'],
    attributes: { hostname: 'dev-k8s-node-02.internal', ip_address: '10.3.1.12', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 8, ram_gb: 32, managed_by: 'kubeadm', is_virtualized: true, sla_tier: 'silver' },
    complianceStatus: 'compliant',
    complianceScore: 83,
    createdBy: 'admin',
    createdAt: '2025-09-10T08:30:00Z',
    updatedAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'ci-s-022',
    ciTypeId: 'server',
    name: 'prod-k8s-master-01',
    shortDescription: 'Kubernetes master/control-plane node (prod)',
    status: 'active',
    criticality: 'critical',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A9',
    environment: 'production',
    tags: ['kubernetes', 'k8s', 'control-plane'],
    attributes: { hostname: 'prod-k8s-master-01.internal', ip_address: '10.0.4.10', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 8, ram_gb: 32, managed_by: 'kubeadm', is_virtualized: false, sla_tier: 'platinum' },
    complianceStatus: 'compliant',
    complianceScore: 96,
    createdBy: 'admin',
    createdAt: '2025-10-01T08:00:00Z',
    updatedAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'ci-s-023',
    ciTypeId: 'server',
    name: 'prod-k8s-worker-01',
    shortDescription: 'Kubernetes worker node #1 (prod)',
    status: 'active',
    criticality: 'high',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A10',
    environment: 'production',
    tags: ['kubernetes', 'k8s', 'worker'],
    attributes: { hostname: 'prod-k8s-worker-01.internal', ip_address: '10.0.4.11', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 16, ram_gb: 64, managed_by: 'kubeadm', is_virtualized: false, sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 93,
    createdBy: 'admin',
    createdAt: '2025-10-01T09:00:00Z',
    updatedAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'ci-s-024',
    ciTypeId: 'server',
    name: 'prod-k8s-worker-02',
    shortDescription: 'Kubernetes worker node #2 (prod)',
    status: 'active',
    criticality: 'high',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack A11',
    environment: 'production',
    tags: ['kubernetes', 'k8s', 'worker'],
    attributes: { hostname: 'prod-k8s-worker-02.internal', ip_address: '10.0.4.12', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 16, ram_gb: 64, managed_by: 'kubeadm', is_virtualized: false, sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 92,
    createdBy: 'admin',
    createdAt: '2025-10-02T09:00:00Z',
    updatedAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'ci-s-025',
    ciTypeId: 'server',
    name: 'prod-nfs-01',
    shortDescription: 'NFS shared file server for application pods',
    status: 'active',
    criticality: 'medium',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1 - Rack B8',
    environment: 'production',
    tags: ['nfs', 'storage', 'shared'],
    attributes: { hostname: 'prod-nfs-01.internal', ip_address: '10.0.5.10', os_type: 'linux', os_version: 'Ubuntu 22.04 LTS', cpu_cores: 4, ram_gb: 8, managed_by: 'ansible', is_virtualized: false, sla_tier: 'silver' },
    complianceStatus: 'compliant',
    complianceScore: 84,
    createdBy: 'admin',
    createdAt: '2025-11-01T08:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },

  // ── Additional Databases ─────────────────────────────────────────────────
  {
    id: 'ci-034',
    ciTypeId: 'database',
    name: 'prod-mysql-01',
    shortDescription: 'Primary MySQL database for HR and Finance modules',
    status: 'active',
    criticality: 'critical',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack B6',
    environment: 'production',
    tags: ['mysql', 'primary', 'hr', 'finance'],
    attributes: { db_type: 'mysql', db_version: '8.0.32', host_server: 'prod-db-01.internal', port: 3306, schema_count: 5, backup_schedule: 'daily', owner_email: 'levanc@company.com', sla_tier: 'platinum' },
    complianceStatus: 'compliant',
    complianceScore: 97,
    createdBy: 'admin',
    createdAt: '2025-03-01T08:00:00Z',
    updatedAt: '2026-03-05T08:00:00Z',
  },
  {
    id: 'ci-035',
    ciTypeId: 'database',
    name: 'dev-postgresql-01',
    shortDescription: 'Development PostgreSQL database for CMPlan team',
    status: 'active',
    criticality: 'low',
    owner: 'Hoang Van E',
    department: 'Platform Engineering',
    location: 'DC2 - Rack C3',
    environment: 'development',
    tags: ['postgresql', 'dev', 'cmplan'],
    attributes: { db_type: 'postgresql', db_version: '15.3', host_server: 'dev-app-01.internal', port: 5432, schema_count: 3, backup_schedule: 'weekly', owner_email: 'hoangvane@company.com', sla_tier: 'standard' },
    complianceStatus: 'non_compliant',
    complianceScore: 48,
    createdBy: 'hoangvane',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-04-15T08:00:00Z',
  },
  {
    id: 'ci-036',
    ciTypeId: 'database',
    name: 'prod-elasticsearch-01',
    shortDescription: 'Elasticsearch cluster for full-text search and log indexing',
    status: 'active',
    criticality: 'high',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack B7',
    environment: 'production',
    tags: ['elasticsearch', 'search', 'logs'],
    attributes: { db_type: 'elasticsearch', db_version: '8.11.0', host_server: 'prod-db-02.internal', port: 9200, schema_count: 12, backup_schedule: 'daily', owner_email: 'levanc@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 86,
    createdBy: 'levanc',
    createdAt: '2025-05-10T08:00:00Z',
    updatedAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'ci-037',
    ciTypeId: 'database',
    name: 'prod-clickhouse-01',
    shortDescription: 'ClickHouse OLAP database for analytics and reporting',
    status: 'active',
    criticality: 'medium',
    owner: 'Le Van C',
    department: 'Data Engineering',
    location: 'DC1 - Rack B8',
    environment: 'production',
    tags: ['clickhouse', 'olap', 'analytics'],
    attributes: { db_type: 'clickhouse', db_version: '23.10', host_server: 'prod-db-02.internal', port: 8123, schema_count: 6, backup_schedule: 'daily', owner_email: 'levanc@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 82,
    createdBy: 'levanc',
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2026-02-28T08:00:00Z',
  },
  {
    id: 'ci-038',
    ciTypeId: 'database',
    name: 'stage-redis-01',
    shortDescription: 'Staging Redis instance for cache and session testing',
    status: 'active',
    criticality: 'low',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'DC2 - Rack C4',
    environment: 'staging',
    tags: ['redis', 'cache', 'staging'],
    attributes: { db_type: 'redis', db_version: '7.0.12', host_server: 'stage-web-01.internal', port: 6379, schema_count: 1, backup_schedule: 'none', owner_email: 'trantib@company.com', sla_tier: 'standard' },
    complianceStatus: 'compliant',
    complianceScore: 70,
    createdBy: 'trantib',
    createdAt: '2025-06-15T08:00:00Z',
    updatedAt: '2025-12-01T08:00:00Z',
  },

  // ── Additional Cloud Services ─────────────────────────────────────────────
  {
    id: 'ci-039',
    ciTypeId: 'cloud_service',
    name: 'AWS RDS - Finance DB',
    shortDescription: 'Managed AWS RDS MySQL instance for Finance Portal',
    status: 'active',
    criticality: 'critical',
    owner: 'Le Van C',
    department: 'Finance',
    location: 'AWS ap-southeast-1',
    environment: 'production',
    tags: ['rds', 'aws', 'mysql', 'finance'],
    attributes: { cloud_provider: 'aws', region: 'ap-southeast-1', account_id: '123456789012', monthly_cost_usd: 480, owner_email: 'levanc@company.com', sla_tier: 'platinum' },
    complianceStatus: 'compliant',
    complianceScore: 95,
    createdBy: 'levanc',
    createdAt: '2025-04-15T08:00:00Z',
    updatedAt: '2026-03-10T08:00:00Z',
  },
  {
    id: 'ci-040',
    ciTypeId: 'cloud_service',
    name: 'AWS Lambda - Notification',
    shortDescription: 'Serverless Lambda functions for notification processing',
    status: 'active',
    criticality: 'medium',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'AWS ap-southeast-1',
    environment: 'production',
    tags: ['lambda', 'aws', 'serverless', 'notification'],
    attributes: { cloud_provider: 'aws', region: 'ap-southeast-1', account_id: '123456789012', monthly_cost_usd: 60, owner_email: 'nguyenvana@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 88,
    createdBy: 'nguyenvana',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'ci-041',
    ciTypeId: 'cloud_service',
    name: 'GCP GKE Dev Cluster',
    shortDescription: 'Google Kubernetes Engine cluster for development workloads',
    status: 'active',
    criticality: 'low',
    owner: 'Tran Thi B',
    department: 'DevOps',
    location: 'GCP asia-southeast1',
    environment: 'development',
    tags: ['gke', 'gcp', 'kubernetes', 'dev'],
    attributes: { cloud_provider: 'gcp', region: 'asia-southeast1', account_id: 'proj-dev-001', monthly_cost_usd: 320, owner_email: 'trantib@company.com', sla_tier: 'standard' },
    complianceStatus: 'compliant',
    complianceScore: 74,
    createdBy: 'trantib',
    createdAt: '2025-11-01T08:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
  },

  // ── Additional Middlewares ────────────────────────────────────────────────
  {
    id: 'ci-042',
    ciTypeId: 'middleware',
    name: 'Kafka Cluster (Prod)',
    shortDescription: 'Production Apache Kafka cluster for event streaming',
    status: 'active',
    criticality: 'critical',
    owner: 'Nguyen Van A',
    department: 'Platform Engineering',
    location: 'DC1',
    environment: 'production',
    tags: ['kafka', 'event-streaming', 'async'],
    attributes: { owner_email: 'nguyenvana@company.com', sla_tier: 'platinum' },
    complianceStatus: 'compliant',
    complianceScore: 92,
    createdBy: 'nguyenvana',
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2026-02-15T08:00:00Z',
  },
  {
    id: 'ci-043',
    ciTypeId: 'middleware',
    name: 'Nginx API Gateway',
    shortDescription: 'Nginx-based API gateway for routing and rate limiting',
    status: 'active',
    criticality: 'high',
    owner: 'Vu Thi F',
    department: 'Network Operations',
    location: 'DC1',
    environment: 'production',
    tags: ['nginx', 'gateway', 'reverse-proxy'],
    attributes: { owner_email: 'vuthif@company.com', sla_tier: 'gold' },
    complianceStatus: 'compliant',
    complianceScore: 89,
    createdBy: 'admin',
    createdAt: '2025-03-20T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },

  // ── Additional Network Devices ────────────────────────────────────────────
  {
    id: 'ci-044',
    ciTypeId: 'network_device',
    name: 'Core Switch DC2',
    shortDescription: 'Cisco Nexus core switch, DC2 spine',
    status: 'active',
    criticality: 'critical',
    owner: 'Vu Thi F',
    department: 'Network Operations',
    location: 'DC2 - Rack NET-01',
    environment: 'production',
    tags: ['cisco', 'nexus', 'core-switch', 'dc2'],
    attributes: { owner_email: 'vuthif@company.com', sla_tier: 'platinum', lifecycle_phase: 'operate' },
    complianceStatus: 'compliant',
    complianceScore: 100,
    createdBy: 'admin',
    createdAt: '2024-12-15T08:00:00Z',
    updatedAt: '2025-10-01T08:00:00Z',
  },
  {
    id: 'ci-045',
    ciTypeId: 'network_device',
    name: 'DC1 Perimeter Firewall',
    shortDescription: 'Palo Alto perimeter firewall for DC1 ingress/egress traffic',
    status: 'active',
    criticality: 'critical',
    owner: 'Vu Thi F',
    department: 'Network Operations',
    location: 'DC1 - Rack NET-02',
    environment: 'production',
    tags: ['palo-alto', 'firewall', 'security', 'dc1'],
    attributes: { owner_email: 'vuthif@company.com', sla_tier: 'platinum', lifecycle_phase: 'operate' },
    complianceStatus: 'compliant',
    complianceScore: 100,
    createdBy: 'admin',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2025-09-01T08:00:00Z',
  },
]

// ── CI Relationships ──────────────────────────────────────────────────────────
export const MOCK_CI_RELATIONSHIPS = [
  {
    id: 'rel-001',
    sourceId: 'ci-006',
    targetId: 'ci-007',
    relationshipType: 'depends_on',
    description: 'CRM Portal calls Business Plan API',
    expiredDate: '2026-05-14T00:00:00Z',
    createdBy: 'admin',
    createdAt: '2025-05-11T08:00:00Z',
  },
  {
    id: 'rel-002',
    sourceId: 'ci-007',
    targetId: 'ci-004',
    relationshipType: 'depends_on',
    description: 'Business Plan API reads/writes to main PostgreSQL',
    expiredDate: '2026-05-14T00:00:00Z',
    createdBy: 'admin',
    createdAt: '2025-02-06T08:00:00Z',
  },
  {
    id: 'rel-003',
    sourceId: 'ci-007',
    targetId: 'ci-005',
    relationshipType: 'depends_on',
    description: 'API depends on Redis for session caching',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-04-02T08:00:00Z',
  },
  {
    id: 'rel-004',
    sourceId: 'ci-006',
    targetId: 'ci-001',
    relationshipType: 'runs_on',
    description: 'CRM Portal served via prod-web-01',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-05-12T08:00:00Z',
  },
  {
    id: 'rel-005',
    sourceId: 'ci-007',
    targetId: 'ci-014',
    relationshipType: 'uses',
    description: 'API publishes events to RabbitMQ',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-08-02T08:00:00Z',
  },
  {
    id: 'rel-006',
    sourceId: 'ci-001',
    targetId: 'ci-009',
    relationshipType: 'connects_to',
    description: 'Web servers connect through core switch',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-02-02T08:00:00Z',
  },
  {
    id: 'rel-007',
    sourceId: 'ci-004',
    targetId: 'ci-013',
    relationshipType: 'uses',
    description: 'PostgreSQL data stored on NetApp SAN',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-02-07T08:00:00Z',
  },
  {
    id: 'rel-008',
    sourceId: 'ci-011',
    targetId: 'ci-006',
    relationshipType: 'hosts',
    description: 'AKS cluster hosts CRM Portal containers',
    expiredDate: '2026-12-31T00:00:00Z',
    createdBy: 'admin',
    createdAt: '2025-06-02T08:00:00Z',
  },
  {
    id: 'rel-009',
    sourceId: 'ci-011',
    targetId: 'ci-007',
    relationshipType: 'hosts',
    description: 'AKS cluster hosts Business Plan API containers',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2025-06-15T08:00:00Z',
  },
  {
    id: 'rel-010',
    sourceId: 'ci-011',
    targetId: 'ci-008',
    relationshipType: 'hosts',
    description: 'AKS cluster hosts CMPlan API (dev)',
    expiredDate: null,
    createdBy: 'admin',
    createdAt: '2026-01-05T08:00:00Z',
  },

  // application → server : runs_on
  { id: 'rel-011', sourceId: 'ci-016', targetId: 'ci-026', relationshipType: 'runs_on',    description: 'HR System runs on prod-app-01',                        expiredDate: null, createdBy: 'admin', createdAt: '2025-03-10T08:00:00Z' },
  { id: 'rel-012', sourceId: 'ci-017', targetId: 'ci-026', relationshipType: 'runs_on',    description: 'Finance Portal runs on prod-app-01',                   expiredDate: null, createdBy: 'admin', createdAt: '2025-04-15T08:00:00Z' },
  { id: 'rel-013', sourceId: 'ci-020', targetId: 'ci-027', relationshipType: 'runs_on',    description: 'Auth Service runs on prod-app-02',                     expiredDate: null, createdBy: 'admin', createdAt: '2025-01-20T08:00:00Z' },
  { id: 'rel-014', sourceId: 'ci-022', targetId: 'ci-027', relationshipType: 'runs_on',    description: 'Mobile API Gateway runs on prod-app-02',               expiredDate: null, createdBy: 'admin', createdAt: '2025-08-10T08:00:00Z' },

  // application → database : depends_on
  { id: 'rel-015', sourceId: 'ci-016', targetId: 'ci-034', relationshipType: 'depends_on', description: 'HR System depends on prod-mysql-01',                   expiredDate: null, createdBy: 'admin', createdAt: '2025-03-10T08:00:00Z' },
  { id: 'rel-016', sourceId: 'ci-017', targetId: 'ci-034', relationshipType: 'depends_on', description: 'Finance Portal depends on prod-mysql-01',              expiredDate: null, createdBy: 'admin', createdAt: '2025-04-15T08:00:00Z' },
  { id: 'rel-017', sourceId: 'ci-018', targetId: 'ci-004', relationshipType: 'depends_on', description: 'CMPlan Web Portal depends on prod-postgresql-01',      expiredDate: null, createdBy: 'admin', createdAt: '2026-01-10T08:00:00Z' },
  { id: 'rel-018', sourceId: 'ci-020', targetId: 'ci-005', relationshipType: 'depends_on', description: 'Auth Service depends on Redis for token storage',      expiredDate: null, createdBy: 'admin', createdAt: '2025-01-20T08:00:00Z' },
  { id: 'rel-019', sourceId: 'ci-021', targetId: 'ci-037', relationshipType: 'depends_on', description: 'Report Service depends on ClickHouse for analytics',   expiredDate: null, createdBy: 'admin', createdAt: '2025-07-01T08:00:00Z' },
  { id: 'rel-020', sourceId: 'ci-021', targetId: 'ci-034', relationshipType: 'depends_on', description: 'Report Service depends on MySQL for source data',      expiredDate: null, createdBy: 'admin', createdAt: '2025-07-01T08:00:00Z' },

  // application → middleware : uses
  { id: 'rel-021', sourceId: 'ci-019', targetId: 'ci-042', relationshipType: 'uses',       description: 'Notification Service uses Kafka for async events',     expiredDate: null, createdBy: 'admin', createdAt: '2025-06-01T08:00:00Z' },
  { id: 'rel-022', sourceId: 'ci-024', targetId: 'ci-043', relationshipType: 'uses',       description: 'Admin Dashboard uses Nginx API Gateway',               expiredDate: null, createdBy: 'admin', createdAt: '2025-05-20T08:00:00Z' },
  { id: 'rel-023', sourceId: 'ci-022', targetId: 'ci-043', relationshipType: 'uses',       description: 'Mobile API Gateway routes through Nginx',              expiredDate: null, createdBy: 'admin', createdAt: '2025-08-10T08:00:00Z' },

  // application → cloud_service : uses
  { id: 'rel-024', sourceId: 'ci-017', targetId: 'ci-039', relationshipType: 'uses',       description: 'Finance Portal uses AWS RDS for managed DB',           expiredDate: null, createdBy: 'admin', createdAt: '2025-04-15T08:00:00Z' },
  { id: 'rel-025', sourceId: 'ci-023', targetId: 'ci-010', relationshipType: 'uses',       description: 'Data Export Service writes to AWS S3 - Media Storage', expiredDate: null, createdBy: 'admin', createdAt: '2025-10-01T08:00:00Z' },

  // application → application : depends_on
  { id: 'rel-026', sourceId: 'ci-018', targetId: 'ci-020', relationshipType: 'depends_on', description: 'CMPlan Web Portal depends on Auth Service for login',  expiredDate: null, createdBy: 'admin', createdAt: '2026-01-10T08:00:00Z' },
  { id: 'rel-027', sourceId: 'ci-019', targetId: 'ci-020', relationshipType: 'depends_on', description: 'Notification Service depends on Auth Service',         expiredDate: null, createdBy: 'admin', createdAt: '2025-06-01T08:00:00Z' },
  { id: 'rel-028', sourceId: 'ci-016', targetId: 'ci-020', relationshipType: 'depends_on', description: 'HR System depends on Auth Service for SSO',            expiredDate: null, createdBy: 'admin', createdAt: '2025-03-10T08:00:00Z' },

  // application → network_device : monitors
  { id: 'rel-029', sourceId: 'ci-025', targetId: 'ci-009', relationshipType: 'monitors',   description: 'Monitoring Agent monitors Core Switch DC1',            expiredDate: null, createdBy: 'admin', createdAt: '2025-02-15T08:00:00Z' },
  { id: 'rel-030', sourceId: 'ci-025', targetId: 'ci-044', relationshipType: 'monitors',   description: 'Monitoring Agent monitors Core Switch DC2',            expiredDate: null, createdBy: 'admin', createdAt: '2025-02-15T08:00:00Z' },

  // server → network_device : connects_to
  { id: 'rel-031', sourceId: 'ci-026', targetId: 'ci-044', relationshipType: 'connects_to', description: 'prod-app-01 connects to Core Switch DC2',            expiredDate: null, createdBy: 'admin', createdAt: '2025-02-01T08:00:00Z' },
  { id: 'rel-032', sourceId: 'ci-027', targetId: 'ci-044', relationshipType: 'connects_to', description: 'prod-app-02 connects to Core Switch DC2',            expiredDate: null, createdBy: 'admin', createdAt: '2025-02-01T08:00:00Z' },
  { id: 'rel-033', sourceId: 'ci-028', targetId: 'ci-009', relationshipType: 'connects_to', description: 'prod-db-server-01 connects to Core Switch DC1',      expiredDate: null, createdBy: 'admin', createdAt: '2025-01-15T08:00:00Z' },

  // server → storage : uses
  { id: 'rel-034', sourceId: 'ci-026', targetId: 'ci-013', relationshipType: 'uses',       description: 'prod-app-01 uses NetApp SAN for persistent storage',  expiredDate: null, createdBy: 'admin', createdAt: '2025-02-01T08:00:00Z' },
  { id: 'rel-035', sourceId: 'ci-028', targetId: 'ci-013', relationshipType: 'uses',       description: 'prod-db-server-01 uses NetApp SAN for data storage',  expiredDate: null, createdBy: 'admin', createdAt: '2025-01-15T08:00:00Z' },

  // server → server : backs_up
  { id: 'rel-036', sourceId: 'ci-033', targetId: 'ci-026', relationshipType: 'backs_up',   description: 'prod-backup-01 backs up prod-app-01',                  expiredDate: null, createdBy: 'admin', createdAt: '2025-09-01T08:00:00Z' },

  // network_device → server : connects_to
  { id: 'rel-037', sourceId: 'ci-044', targetId: 'ci-026', relationshipType: 'connects_to', description: 'Core Switch DC2 connects to prod-app-01',            expiredDate: null, createdBy: 'admin', createdAt: '2025-02-01T08:00:00Z' },
  { id: 'rel-038', sourceId: 'ci-009', targetId: 'ci-028', relationshipType: 'connects_to', description: 'Core Switch DC1 connects to prod-db-server-01',      expiredDate: null, createdBy: 'admin', createdAt: '2025-01-15T08:00:00Z' },

  // network_device → network_device : connects_to
  { id: 'rel-039', sourceId: 'ci-044', targetId: 'ci-045', relationshipType: 'connects_to', description: 'Core Switch DC2 connects to DC1 Perimeter Firewall', expiredDate: null, createdBy: 'admin', createdAt: '2024-12-15T08:00:00Z' },

  // virtual_machine → server : runs_on
  { id: 'rel-040', sourceId: 'ci-012', targetId: 'ci-028', relationshipType: 'runs_on',    description: 'VM-worker-01 runs on prod-db-server-01',               expiredDate: null, createdBy: 'admin', createdAt: '2025-07-01T08:00:00Z' },

  // virtual_machine → storage : uses
  { id: 'rel-041', sourceId: 'ci-012', targetId: 'ci-013', relationshipType: 'uses',       description: 'VM-worker-01 uses NetApp SAN for batch output',       expiredDate: null, createdBy: 'admin', createdAt: '2025-07-01T08:00:00Z' },

  // database → server : runs_on
  { id: 'rel-042', sourceId: 'ci-034', targetId: 'ci-028', relationshipType: 'runs_on',    description: 'prod-mysql-01 runs on prod-db-server-01',              expiredDate: null, createdBy: 'admin', createdAt: '2025-03-01T08:00:00Z' },
  { id: 'rel-043', sourceId: 'ci-035', targetId: 'ci-030', relationshipType: 'runs_on',    description: 'dev-postgresql-01 runs on dev-app-01',                 expiredDate: null, createdBy: 'admin', createdAt: '2026-01-10T08:00:00Z' },
  { id: 'rel-044', sourceId: 'ci-036', targetId: 'ci-029', relationshipType: 'runs_on',    description: 'prod-elasticsearch-01 runs on prod-db-server-02',      expiredDate: null, createdBy: 'admin', createdAt: '2025-05-10T08:00:00Z' },

  // database → storage : uses
  { id: 'rel-045', sourceId: 'ci-034', targetId: 'ci-013', relationshipType: 'uses',       description: 'prod-mysql-01 uses NetApp SAN for data files',        expiredDate: null, createdBy: 'admin', createdAt: '2025-03-01T08:00:00Z' },

  // middleware → server : runs_on
  { id: 'rel-046', sourceId: 'ci-042', targetId: 'ci-032', relationshipType: 'runs_on',    description: 'Kafka Cluster runs on prod-mq-server-01',              expiredDate: null, createdBy: 'admin', createdAt: '2025-07-01T08:00:00Z' },
  { id: 'rel-047', sourceId: 'ci-043', targetId: 'ci-001', relationshipType: 'runs_on',    description: 'Nginx API Gateway runs on prod-web-01',                expiredDate: null, createdBy: 'admin', createdAt: '2025-03-20T08:00:00Z' },
  { id: 'rel-048', sourceId: 'ci-014', targetId: 'ci-032', relationshipType: 'runs_on',    description: 'RabbitMQ Cluster runs on prod-mq-server-01',           expiredDate: null, createdBy: 'admin', createdAt: '2025-08-01T08:00:00Z' },

  // middleware → application : connects_to
  { id: 'rel-049', sourceId: 'ci-042', targetId: 'ci-019', relationshipType: 'connects_to', description: 'Kafka connects to Notification Service consumers',   expiredDate: null, createdBy: 'admin', createdAt: '2025-07-01T08:00:00Z' },
  { id: 'rel-050', sourceId: 'ci-043', targetId: 'ci-006', relationshipType: 'connects_to', description: 'Nginx API Gateway routes to CRM Web Portal',         expiredDate: null, createdBy: 'admin', createdAt: '2025-03-20T08:00:00Z' },

  // cloud_service → application : hosts
  { id: 'rel-051', sourceId: 'ci-040', targetId: 'ci-019', relationshipType: 'hosts',      description: 'AWS Lambda hosts Notification Service functions',      expiredDate: null, createdBy: 'admin', createdAt: '2025-06-01T08:00:00Z' },
  { id: 'rel-052', sourceId: 'ci-041', targetId: 'ci-018', relationshipType: 'hosts',      description: 'GCP GKE Dev Cluster hosts CMPlan Web Portal (dev)',    expiredDate: null, createdBy: 'admin', createdAt: '2025-11-01T08:00:00Z' },

  // cloud_service → database : hosts
  { id: 'rel-053', sourceId: 'ci-039', targetId: 'ci-034', relationshipType: 'hosts',      description: 'AWS RDS hosts prod-mysql-01 as managed instance',      expiredDate: null, createdBy: 'admin', createdAt: '2025-04-15T08:00:00Z' },

  // cloud_service → cloud_service : depends_on
  { id: 'rel-054', sourceId: 'ci-041', targetId: 'ci-011', relationshipType: 'depends_on', description: 'GCP GKE Dev Cluster depends on Azure AKS for shared services', expiredDate: null, createdBy: 'admin', createdAt: '2025-11-01T08:00:00Z' },
  { id: 'rel-055', sourceId: 'ci-040', targetId: 'ci-010', relationshipType: 'depends_on', description: 'AWS Lambda depends on S3 for output storage',          expiredDate: null, createdBy: 'admin', createdAt: '2025-06-01T08:00:00Z' },
]

// ── CI Groups ─────────────────────────────────────────────────────────────────
export const MOCK_CI_GROUPS = [
  {
    id: 'grp-001',
    name: 'CRM Business Service',
    description: 'All CIs supporting the CRM product suite',
    groupType: 'service',
    owner: 'Pham Thi D',
    color: '#13c2c2',
    ciIds: ['ci-001', 'ci-002', 'ci-004', 'ci-005', 'ci-006', 'ci-007', 'ci-014'],
    createdAt: '2025-05-15T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'grp-002',
    name: 'Production Environment',
    description: 'All production CIs',
    groupType: 'environment',
    owner: 'Nguyen Van A',
    color: '#f5222d',
    ciIds: ['ci-001', 'ci-002', 'ci-004', 'ci-005', 'ci-006', 'ci-007', 'ci-009', 'ci-010', 'ci-011', 'ci-013', 'ci-014'],
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'grp-003',
    name: 'Platform Engineering Stack',
    description: 'Infrastructure managed by Platform Engineering',
    groupType: 'team',
    owner: 'Hoang Van E',
    color: '#1890ff',
    ciIds: ['ci-001', 'ci-002', 'ci-007', 'ci-008', 'ci-011', 'ci-014'],
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
]

// ── Compliance Policies ───────────────────────────────────────────────────────
export const MOCK_COMPLIANCE_POLICIES = [
  {
    id: 'pol-001',
    name: 'CI Must Have Owner',
    description: 'Every CI must have an owner email defined.',
    ciTypeId: null,
    rules: [
      {
        id: 'rule-001',
        field: 'attributes.owner_email',
        operator: 'not_empty',
        value: null,
        message: 'Owner email is required for all CIs.',
      },
    ],
    severity: 'high',
    isActive: true,
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
  },
  {
    id: 'pol-002',
    name: 'Server Must Have OS Info',
    description: 'All server CIs must specify OS type and version.',
    ciTypeId: 'server',
    rules: [
      {
        id: 'rule-002',
        field: 'attributes.os_type',
        operator: 'not_empty',
        value: null,
        message: 'OS Type is required for servers.',
      },
      {
        id: 'rule-003',
        field: 'attributes.hostname',
        operator: 'not_empty',
        value: null,
        message: 'Hostname is required for servers.',
      },
    ],
    severity: 'critical',
    isActive: true,
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
  },
  {
    id: 'pol-003',
    name: 'Database Must Have Backup Schedule',
    description: 'Production/staging databases must have a backup schedule defined.',
    ciTypeId: 'database',
    rules: [
      {
        id: 'rule-004',
        field: 'attributes.backup_schedule',
        operator: 'not_empty',
        value: null,
        message: 'Backup schedule must be configured.',
      },
      {
        id: 'rule-005',
        field: 'attributes.backup_schedule',
        operator: 'not_equals',
        value: 'none',
        message: 'Backup schedule cannot be "None" for databases.',
      },
    ],
    severity: 'critical',
    isActive: true,
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2025-02-01T08:00:00Z',
  },
  {
    id: 'pol-004',
    name: 'Application Must Have Repository',
    description: 'All application CIs should link to a source repository.',
    ciTypeId: 'application',
    rules: [
      {
        id: 'rule-006',
        field: 'attributes.repository_url',
        operator: 'not_empty',
        value: null,
        message: 'Repository URL should be provided.',
      },
    ],
    severity: 'medium',
    isActive: true,
    createdAt: '2025-03-01T08:00:00Z',
    updatedAt: '2025-03-01T08:00:00Z',
  },
]

// ── CI Audit Log ─────────────────────────────────────────────────────────────
// Actions: ci_created | ci_updated | ci_status_changed | rel_added | rel_removed
export const MOCK_CI_AUDIT_LOG = [
  // ── prod-web-01 (ci-001) ─────────────────────────────────────────
  {
    id: 'log-001', ciId: 'ci-001', action: 'ci_created', actor: 'admin',
    timestamp: '2025-01-15T09:00:00Z', meta: {},
  },
  {
    id: 'log-002', ciId: 'ci-001', action: 'ci_updated', actor: 'alice.vu',
    timestamp: '2025-03-10T14:30:00Z',
    meta: { changes: [{ field: 'owner', from: 'admin', to: 'alice.vu' }, { field: 'department', from: 'IT', to: 'Platform Engineering' }] },
  },
  {
    id: 'log-003', ciId: 'ci-001', action: 'rel_added', actor: 'admin',
    timestamp: '2025-02-02T08:00:00Z',
    meta: { relId: 'rel-006', relType: 'connects_to', peerId: 'ci-009', peerName: 'Core Switch SW-01', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-004', ciId: 'ci-001', action: 'ci_status_changed', actor: 'alice.vu',
    timestamp: '2025-09-01T07:00:00Z',
    meta: { changes: [{ field: 'status', from: 'active', to: 'maintenance' }] },
  },
  {
    id: 'log-005', ciId: 'ci-001', action: 'ci_status_changed', actor: 'alice.vu',
    timestamp: '2025-09-03T09:30:00Z',
    meta: { changes: [{ field: 'status', from: 'maintenance', to: 'active' }] },
  },
  // ── CRM Portal (ci-006) ──────────────────────────────────────────
  {
    id: 'log-010', ciId: 'ci-006', action: 'ci_created', actor: 'admin',
    timestamp: '2025-01-20T10:00:00Z', meta: {},
  },
  {
    id: 'log-011', ciId: 'ci-006', action: 'ci_status_changed', actor: 'john.doe',
    timestamp: '2025-03-15T11:20:00Z',
    meta: { changes: [{ field: 'status', from: 'active', to: 'maintenance' }] },
  },
  {
    id: 'log-012', ciId: 'ci-006', action: 'ci_status_changed', actor: 'john.doe',
    timestamp: '2025-03-16T09:00:00Z',
    meta: { changes: [{ field: 'status', from: 'maintenance', to: 'active' }] },
  },
  {
    id: 'log-013', ciId: 'ci-006', action: 'rel_added', actor: 'admin',
    timestamp: '2025-05-11T08:00:00Z',
    meta: { relId: 'rel-001', relType: 'depends_on', peerId: 'ci-007', peerName: 'Business Plan API', direction: 'outbound', expiredDate: '2026-05-14T00:00:00Z' },
  },
  {
    id: 'log-014', ciId: 'ci-006', action: 'rel_added', actor: 'admin',
    timestamp: '2025-05-12T08:00:00Z',
    meta: { relId: 'rel-004', relType: 'runs_on', peerId: 'ci-001', peerName: 'prod-web-01', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-015', ciId: 'ci-006', action: 'rel_removed', actor: 'john.doe',
    timestamp: '2025-11-20T14:45:00Z',
    meta: { relId: 'rel-old-01', relType: 'connected_to', peerId: 'ci-003', peerName: 'prod-db-02', direction: 'outbound' },
  },
  {
    id: 'log-016', ciId: 'ci-006', action: 'ci_updated', actor: 'john.doe',
    timestamp: '2025-12-01T10:00:00Z',
    meta: { changes: [{ field: 'criticality', from: 'medium', to: 'high' }] },
  },
  // ── Business Plan API (ci-007) ──────────────────────────────────
  {
    id: 'log-020', ciId: 'ci-007', action: 'ci_created', actor: 'admin',
    timestamp: '2025-01-22T10:00:00Z', meta: {},
  },
  {
    id: 'log-021', ciId: 'ci-007', action: 'ci_updated', actor: 'jane.smith',
    timestamp: '2025-04-10T15:00:00Z',
    meta: { changes: [{ field: 'criticality', from: 'medium', to: 'high' }] },
  },
  {
    id: 'log-022', ciId: 'ci-007', action: 'rel_added', actor: 'admin',
    timestamp: '2025-02-06T08:00:00Z',
    meta: { relId: 'rel-002', relType: 'depends_on', peerId: 'ci-004', peerName: 'PostgreSQL Main', direction: 'outbound', expiredDate: '2026-05-14T00:00:00Z' },
  },
  {
    id: 'log-023', ciId: 'ci-007', action: 'rel_added', actor: 'admin',
    timestamp: '2025-04-02T08:00:00Z',
    meta: { relId: 'rel-003', relType: 'uses', peerId: 'ci-005', peerName: 'Redis Cache-01', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-024', ciId: 'ci-007', action: 'rel_added', actor: 'admin',
    timestamp: '2025-08-02T08:00:00Z',
    meta: { relId: 'rel-005', relType: 'uses', peerId: 'ci-014', peerName: 'RabbitMQ Cluster', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-025', ciId: 'ci-007', action: 'rel_removed', actor: 'jane.smith',
    timestamp: '2026-01-10T09:15:00Z',
    meta: { relId: 'rel-old-02', relType: 'connected_to', peerId: 'ci-002', peerName: 'prod-web-02', direction: 'inbound' },
  },
  // ── prod-web-01 (ci-001) — attribute & class updates ───────────────────────────────
  {
    id: 'log-030', ciId: 'ci-001', action: 'ci_attr_updated', actor: 'alice.vu',
    timestamp: '2025-06-15T11:00:00Z',
    meta: {
      typeLabel: 'Server',
      changes: [
        { field: 'ip_address', label: 'IP Address', from: '10.0.10.10', to: '10.0.10.15' },
        { field: 'os_version', label: 'OS Version', from: 'Ubuntu 20.04 LTS', to: 'Ubuntu 22.04 LTS' },
      ],
    },
  },
  {
    id: 'log-031', ciId: 'ci-001', action: 'ci_attr_updated', actor: 'alice.vu',
    timestamp: '2025-10-20T09:30:00Z',
    meta: {
      typeLabel: 'Server',
      changes: [
        { field: 'cpu_cores', label: 'CPU Cores', from: 4, to: 8 },
        { field: 'ram_gb', label: 'RAM (GB)', from: 16, to: 32 },
      ],
    },
  },
  {
    id: 'log-032', ciId: 'ci-001', action: 'rel_updated', actor: 'alice.vu',
    timestamp: '2026-02-14T14:00:00Z',
    meta: { relId: 'rel-004', relType: 'runs_on', peerId: 'ci-006', peerName: 'CRM Portal', direction: 'inbound', changes: [{ field: 'expiredDate', from: null, to: '2026-12-31T00:00:00Z' }] },
  },
  // ── CRM Portal (ci-006) — attr + class change ──────────────────────────────────
  {
    id: 'log-033', ciId: 'ci-006', action: 'ci_attr_updated', actor: 'john.doe',
    timestamp: '2025-07-01T10:00:00Z',
    meta: {
      typeLabel: 'Application',
      changes: [
        { field: 'tech_stack', label: 'Tech Stack', from: 'React 17', to: 'React 18 + Vite' },
        { field: 'sla_tier', label: 'SLA Tier', from: 'standard', to: 'gold' },
      ],
    },
  },
  {
    id: 'log-034', ciId: 'ci-006', action: 'ci_type_changed', actor: 'admin',
    timestamp: '2025-08-10T08:30:00Z',
    meta: { fromTypeId: 'type-002', fromTypeName: 'Application', toTypeId: 'type-002', toTypeName: 'Web Application' },
  },
  // ── Business Plan API (ci-007) — attr updates ─────────────────────────────────
  {
    id: 'log-035', ciId: 'ci-007', action: 'ci_attr_updated', actor: 'jane.smith',
    timestamp: '2025-09-05T16:20:00Z',
    meta: {
      typeLabel: 'Application',
      changes: [
        { field: 'api_version', label: 'API Version', from: 'v1.3.0', to: 'v1.4.0' },
        { field: 'sla_tier', label: 'SLA Tier', from: 'gold', to: 'platinum' },
      ],
    },
  },
  {
    id: 'log-036', ciId: 'ci-007', action: 'rel_updated', actor: 'jane.smith',
    timestamp: '2026-03-01T10:00:00Z',
    meta: { relId: 'rel-002', relType: 'depends_on', peerId: 'ci-004', peerName: 'PostgreSQL Main', direction: 'outbound', changes: [{ field: 'expiredDate', from: '2026-05-14T00:00:00Z', to: '2027-05-14T00:00:00Z' }] },
  },
  // ── Azure AKS Cluster - Prod (ci-011) ─────────────────────────────────
  {
    id: 'log-040', ciId: 'ci-011', action: 'ci_created', actor: 'hoangvane',
    timestamp: '2025-06-01T08:00:00Z', meta: {},
  },
  {
    id: 'log-041', ciId: 'ci-011', action: 'ci_updated', actor: 'hoangvane',
    timestamp: '2025-08-15T10:00:00Z',
    meta: { changes: [{ field: 'owner', from: 'admin', to: 'Hoang Van E' }, { field: 'department', from: 'IT', to: 'Platform Engineering' }] },
  },
  {
    id: 'log-042', ciId: 'ci-011', action: 'ci_attr_updated', actor: 'hoangvane',
    timestamp: '2025-10-01T09:00:00Z',
    meta: {
      typeLabel: 'Cloud Service',
      changes: [
        { field: 'monthly_cost_usd', label: 'Monthly Cost (USD)', from: 2400, to: 2800 },
        { field: 'account_id', label: 'Account ID', from: 'sub-abc-000', to: 'sub-abc-def-001' },
      ],
    },
  },
  {
    id: 'log-043', ciId: 'ci-011', action: 'rel_added', actor: 'admin',
    timestamp: '2025-06-02T08:00:00Z',
    meta: { relId: 'rel-008', relType: 'hosts', peerId: 'ci-006', peerName: 'CRM Web Portal', direction: 'outbound', expiredDate: '2026-12-31T00:00:00Z' },
  },
  {
    id: 'log-044', ciId: 'ci-011', action: 'rel_added', actor: 'admin',
    timestamp: '2025-06-15T08:00:00Z',
    meta: { relId: 'rel-009', relType: 'hosts', peerId: 'ci-007', peerName: 'Business Plan API Service', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-045', ciId: 'ci-011', action: 'rel_added', actor: 'admin',
    timestamp: '2026-01-05T08:00:00Z',
    meta: { relId: 'rel-010', relType: 'hosts', peerId: 'ci-008', peerName: 'CMPlan API Service', direction: 'outbound', expiredDate: null },
  },
  {
    id: 'log-046', ciId: 'ci-011', action: 'ci_status_changed', actor: 'hoangvane',
    timestamp: '2026-03-20T14:00:00Z',
    meta: { changes: [{ field: 'status', from: 'active', to: 'maintenance' }] },
  },
  {
    id: 'log-047', ciId: 'ci-011', action: 'ci_status_changed', actor: 'hoangvane',
    timestamp: '2026-03-21T09:30:00Z',
    meta: { changes: [{ field: 'status', from: 'maintenance', to: 'active' }] },
  },
  // ── prod-postgresql-01 (ci-004) ────────────────────────────────────
  {
    id: 'log-050', ciId: 'ci-004', action: 'ci_created', actor: 'admin',
    timestamp: '2025-02-05T08:00:00Z', meta: {},
  },
  {
    id: 'log-051', ciId: 'ci-004', action: 'ci_attr_updated', actor: 'levanc',
    timestamp: '2025-09-10T11:00:00Z',
    meta: {
      typeLabel: 'Database',
      changes: [{ field: 'db_version', label: 'DB Version', from: '14.8', to: '15.3' }],
    },
  },
  {
    id: 'log-052', ciId: 'ci-004', action: 'rel_added', actor: 'admin',
    timestamp: '2025-02-07T08:00:00Z',
    meta: { relId: 'rel-007', relType: 'runs_on', peerId: 'ci-013', peerName: 'NetApp FAS - Primary SAN', direction: 'outbound', expiredDate: null },
  },
]

// ── CI Rule Config (Validation Rules & Relationship Types) ───────────────────
export const MOCK_CI_RULE_CONFIGS = [
  {
    id: 'cr-001',
    category: 'validation_rule',
    name: 'Email',
    value: '/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/',
    description: 'Validate email address format',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-002',
    category: 'validation_rule',
    name: 'Phone',
    value: '/^(\\+84|0)[0-9]{9,10}$/',
    description: 'Validate Vietnamese phone number',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-003',
    category: 'validation_rule',
    name: 'User Name',
    value: '/^[a-zA-Z0-9_]{5,20}$/',
    description: 'Validate username (5–20 chars, no spaces)',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-004',
    category: 'validation_rule',
    name: 'URL',
    value: '/^(https?:\\/\\/)/',
    description: 'Validate URL starts with http or https',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-v-001',
    category: 'validation_rule',
    name: 'Hostname',
    value: '/^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?$/',
    description: 'Validate a valid DNS hostname (RFC 1123)',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-v-002',
    category: 'validation_rule',
    name: 'IP Address',
    value: '/^((25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.){3}(25[0-5]|2[0-4]\\d|[01]?\\d\\d?)$/',
    description: 'Validate IPv4 address format (0.0.0.0 – 255.255.255.255)',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-005',
    category: 'relationship_type',
    name: 'Connected To',
    value: 'connected_to',
    description: 'General connectivity between two CIs',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-006',
    category: 'relationship_type',
    name: 'Depend On',
    value: 'depends_on',
    description: 'CI depends on another CI to function',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-007',
    category: 'relationship_type',
    name: 'Runs On',
    value: 'runs_on',
    description: 'Software CI runs on hardware/OS CI',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-008',
    category: 'relationship_type',
    name: 'Hosts',
    value: 'hosts',
    description: 'Server CI hosts other CIs',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-009',
    category: 'relationship_type',
    name: 'Contains',
    value: 'contains',
    description: 'Group or parent CI contains child CIs',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'cr-010',
    category: 'relationship_type',
    name: 'Monitors',
    value: 'monitors',
    description: 'Monitoring CI watches over target CI',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
]

// ── CRM Directions ───────────────────────────────────────────────────────────
export const MOCK_CRM_DIRECTIONS = [
  {
    id: 'crm-dir-001',
    sourceCIType: 'user',
    destinationCIType: 'email',
    jiraType: 'user',
    createdBy: 'admin',
    updatedBy: 'kdquan',
    createdAt: '2024-11-15T09:00:00Z',
    updatedAt: '2024-12-06T14:30:00Z',
  },
  {
    id: 'crm-dir-002',
    sourceCIType: 'account',
    destinationCIType: 'contact',
    jiraType: 'task',
    createdBy: 'admin',
    updatedBy: 'admin',
    createdAt: '2024-11-20T10:00:00Z',
    updatedAt: '2024-11-20T10:00:00Z',
  },
  {
    id: 'crm-dir-003',
    sourceCIType: 'lead',
    destinationCIType: 'opportunity',
    jiraType: 'story',
    createdBy: 'kdquan',
    updatedBy: 'kdquan',
    createdAt: '2024-12-01T11:00:00Z',
    updatedAt: '2024-12-05T16:00:00Z',
  },
  {
    id: 'crm-dir-004',
    sourceCIType: 'contact',
    destinationCIType: 'account',
    jiraType: 'bug',
    createdBy: 'admin',
    updatedBy: 'thnguyen',
    createdAt: '2024-12-02T08:30:00Z',
    updatedAt: '2024-12-04T09:15:00Z',
  },
  {
    id: 'crm-dir-005',
    sourceCIType: 'user',
    destinationCIType: 'lead',
    jiraType: 'epic',
    createdBy: 'thnguyen',
    updatedBy: 'thnguyen',
    createdAt: '2024-12-03T13:00:00Z',
    updatedAt: '2024-12-03T13:00:00Z',
  },
]

// ── CI Type Relationships ─────────────────────────────────────────────────────
// Each row defines an allowed (sourceType, relationshipType, targetType) triple.
// ciType values match the canonical CI type name; *Value fields carry the human-readable label.
export const MOCK_CI_TYPE_RELATIONSHIPS = [
  { id: 1,  ciTypeSource: 'application',     ciTypeSourceValue: 'Application',     ciTypeTarget: 'server',          ciTypeTargetValue: 'Server',          typeConnection: 'runs_on',     typeConnectionValue: 'Runs On' },
  { id: 2,  ciTypeSource: 'application',     ciTypeSourceValue: 'Application',     ciTypeTarget: 'database',        ciTypeTargetValue: 'Database',        typeConnection: 'depends_on',  typeConnectionValue: 'Depends On' },
  { id: 3,  ciTypeSource: 'application',     ciTypeSourceValue: 'Application',     ciTypeTarget: 'middleware',      ciTypeTargetValue: 'Middleware',      typeConnection: 'uses',        typeConnectionValue: 'Uses' },
  { id: 4,  ciTypeSource: 'application',     ciTypeSourceValue: 'Application',     ciTypeTarget: 'cloud_service',   ciTypeTargetValue: 'Cloud Service',   typeConnection: 'uses',        typeConnectionValue: 'Uses' },
  { id: 5,  ciTypeSource: 'server',          ciTypeSourceValue: 'Server',          ciTypeTarget: 'network_device',  ciTypeTargetValue: 'Network Device',  typeConnection: 'connects_to', typeConnectionValue: 'Connects To' },
  { id: 6,  ciTypeSource: 'server',          ciTypeSourceValue: 'Server',          ciTypeTarget: 'storage',         ciTypeTargetValue: 'Storage',         typeConnection: 'uses',        typeConnectionValue: 'Uses' },
  { id: 7,  ciTypeSource: 'network_device',  ciTypeSourceValue: 'Network Device',  ciTypeTarget: 'server',          ciTypeTargetValue: 'Server',          typeConnection: 'connects_to', typeConnectionValue: 'Connects To' },
  { id: 8,  ciTypeSource: 'virtual_machine', ciTypeSourceValue: 'Virtual Machine', ciTypeTarget: 'server',          ciTypeTargetValue: 'Server',          typeConnection: 'runs_on',     typeConnectionValue: 'Runs On' },
  { id: 9,  ciTypeSource: 'virtual_machine', ciTypeSourceValue: 'Virtual Machine', ciTypeTarget: 'storage',         ciTypeTargetValue: 'Storage',         typeConnection: 'uses',        typeConnectionValue: 'Uses' },
  { id: 10, ciTypeSource: 'cloud_service',   ciTypeSourceValue: 'Cloud Service',   ciTypeTarget: 'application',     ciTypeTargetValue: 'Application',     typeConnection: 'hosts',       typeConnectionValue: 'Hosts' },
  { id: 11, ciTypeSource: 'cloud_service',   ciTypeSourceValue: 'Cloud Service',   ciTypeTarget: 'database',        ciTypeTargetValue: 'Database',        typeConnection: 'hosts',       typeConnectionValue: 'Hosts' },
  { id: 12, ciTypeSource: 'database',        ciTypeSourceValue: 'Database',        ciTypeTarget: 'server',          ciTypeTargetValue: 'Server',          typeConnection: 'runs_on',     typeConnectionValue: 'Runs On' },
  { id: 13, ciTypeSource: 'database',        ciTypeSourceValue: 'Database',        ciTypeTarget: 'storage',         ciTypeTargetValue: 'Storage',         typeConnection: 'uses',        typeConnectionValue: 'Uses' },
  { id: 14, ciTypeSource: 'middleware',      ciTypeSourceValue: 'Middleware',      ciTypeTarget: 'server',          ciTypeTargetValue: 'Server',          typeConnection: 'runs_on',     typeConnectionValue: 'Runs On' },
  { id: 15, ciTypeSource: 'middleware',      ciTypeSourceValue: 'Middleware',      ciTypeTarget: 'application',     ciTypeTargetValue: 'Application',     typeConnection: 'connects_to', typeConnectionValue: 'Connects To' },
  { id: 16, ciTypeSource: 'server',          ciTypeSourceValue: 'Server',          ciTypeTarget: 'server',          ciTypeTargetValue: 'Server',          typeConnection: 'backs_up',    typeConnectionValue: 'Backs Up' },
  { id: 17, ciTypeSource: 'application',     ciTypeSourceValue: 'Application',     ciTypeTarget: 'application',     ciTypeTargetValue: 'Application',     typeConnection: 'depends_on',  typeConnectionValue: 'Depends On' },
  { id: 18, ciTypeSource: 'network_device',  ciTypeSourceValue: 'Network Device',  ciTypeTarget: 'network_device',  ciTypeTargetValue: 'Network Device',  typeConnection: 'connects_to', typeConnectionValue: 'Connects To' },
  { id: 19, ciTypeSource: 'cloud_service',   ciTypeSourceValue: 'Cloud Service',   ciTypeTarget: 'cloud_service',   ciTypeTargetValue: 'Cloud Service',   typeConnection: 'depends_on',  typeConnectionValue: 'Depends On' },
  { id: 20, ciTypeSource: 'application',     ciTypeSourceValue: 'Application',     ciTypeTarget: 'network_device',  ciTypeTargetValue: 'Network Device',  typeConnection: 'monitors',    typeConnectionValue: 'Monitors' },
]
